### ISSUE TITLE
Can tagbar support 'remember folds'?

### ISSUE THREAD

**Issue by jchain** [preservim/tagbar#152]
The tag tree in my tagbar is very long so I fold some tag types. The problem is it seems that tagbar can't remember the folded tags so that once I close the tagbar and re-open it, the folds are lost. It is a bit annoying. Is it possible to add a feature to remember the folds?
Thanks!

**Comment by grafa** [comment]
Hi,

just ran into this and the `g:tagbar_autoshowtag = 2` is amazing. Dunno why but for some files(python) I was getting all my imports unfolded (which was huge wasting of space). Now it's ok.

Well done mate!

**Comment by simonalford42** [comment]
Thank you @im-n1 , I was looking for a way to fold the imports by default and `g:tagbar_autoshowtag = 2` seems to do the trick.
