### ISSUE TITLE
Tagbar seems to not running the right ctags from PATH

### ISSUE THREAD

**Issue by pencilcheck** [preservim/tagbar#154]
I bootstrapped my env using boxen and installed ctags to `/opt/boxen/homebrew/bin/ctrags` with homebrew

When I typed `where ctags` in my shell, the right ctags shows up, this means the PATH is set correctly.

However tagbar seems to be using some other kinds of ctags and keeps telling me to use exuberant tags instead of gnu ctags.

This problem is not solved until I specify directly the bin path in my vimrc with `g:tagbar_ctags_bin`

**Comment by IFCLS** [comment]
![screenshot from 2016-12-01 21-30-19](https://cloud.githubusercontent.com/assets/7093220/20800886/025f293a-b822-11e6-930e-dff0deddbaa0.png)
