### ISSUE TITLE
Allow remapping of keys

### ISSUE THREAD

**Issue by michamos** [preservim/tagbar#159]
Hello,

I use a Dvorak-like keyboard, in which `s` is a motion key. This requires me to map a different key for sorting. For the moment, I just forked your plugin and hardcoded a different value, but it would be much nicer if there was some configurability.

One option would be to provide some variables that the user could override (this is used for example in the [gundo](http://github.com/sjl/gundo.vim) plugin), but since there are a lot of maps in the tagbar window, the solution suggested in #146 with an autocommand is probably better.

**Comment by FlyingWombat** [comment]
Could you please add **all** the key map options to the docs?  
For example: `tagbar_map_togglecaseinsensitive` is missing.
