### ISSUE TITLE
Issue with multiple buffers open

### ISSUE THREAD

**Issue by vincentzhang** [preservim/tagbar#218]
It does not work well when switching between buffers.

**Reproduce**
Open two tabs or two buffers in vim
From buffer1, open and jump into tagbar screen
Switch to buffer2
Switch back to buffer1

**What I Expected**: buffer1 + tagbar both open

**Actual Result**: buffer2 still open, the tagbar screen switches to buffer1

I feel that the expected result would be a nice to have feature if it's not an issue.

**Comment by isharaka** [comment]
Hi @majutsushi,

I think the following change in `function! s:OpenWindow(flags)`  will achieve the desired outcome, as far as I understand it. To me this helps keep the tagbar next to the window of interest.

```    let l:splitright = &splitright
    if g:tagbar_window_local == 1
        let openpos = ''
        let &splitright = g:tagbar_left ? 0 : 1
    endif

    exe 'silent keepalt ' . openpos . mode . width . 'split ' . s:TagbarBufName()
    exe 'silent ' . mode . 'resize ' . width
    unlet s:window_opening

    let &splitright = l:splitright
```

This does not handle switching between windows as expected though. I would like to see tagbar being closed and re-opened in the active window if switched.

**Comment by alerque** [comment]
@isharaka This issue is closed an not the place to track further improvements. I understand that bit of code isn't ready to merge yet, but can I ask that you contribute it as a Draft mode PR so it is easier to test and iterate on?
