### ISSUE TITLE
Error displaying Ruby function prototypes after changing ctags bin

### ISSUE THREAD

**Issue by avivrosenberg** [preservim/tagbar#219]
I've recently configured Tagbar to use [ripper-tags](https://github.com/tmm1/ripper-tags) as the ctags binary with Ruby files. The regular ctags doesn't seem to do a good job creating Ruby tags.

Following the Tagbar documentation, this is how I've configured it:

``` vim
" Configure Tagbar to use ripper-tags with ruby
let g:tagbar_type_ruby = {
            \ 'kinds' : [
                \ 'm:modules',
                \ 'c:classes',
                \ 'f:methods',
                \ 'F:singleton methods',
                \ 'C:constants'
            \ ],
            \ 'ctagsbin':  'ripper-tags',
            \ 'ctagsargs': ['-f', '-']
            \ }
```

(I also modified the `kinds` array and added the `'C:constants'` line because without that it didn't seem to work at all, various errors reported.)

Anyways, the above configuration seems to work nicely for viewing and jumping to tags. However, when I press Space to see a function prototype, I get the following error:

```
Error detected while processing function <SNR>137_ShowPrototype..586:
line    6:
E684: list index out of range: 0
E15: Invalid expression: getbufline(bufnr, self.fields.line)[0]
-1
```

An interesting thing to note is that this only happens when pressing Space to view the **non-current** tag. In other words, viewing the prototype of the function I'm currently in **does** work.

Thanks :)

**Comment by mikedfunk** [comment]
Thanks for this, it got tagbar working for me in ruby 👍
