### ISSUE TITLE
Enable "Comment Section" Entries?

### ISSUE THREAD

**Issue by jonahx** [preservim/tagbar#302]
Often (eg, in a .vimrc) I'll created labelled "sections" of the file using a comment header, like so:

``` vim
"""""""""""""""""""""""""""""""""""
"  Mappings
"""""""""""""""""""""""""""""""""""
let mapleader = ","

" Quickly edit vimrc
nmap <leader>~ :e ~/.vimrc<CR>

" Copy/paste (works in terminal)
vnoremap <C-c> "*y
inoremap <C-v> <C-r><C-p>*
```

I'd like these sections to show up as entries in my tagbar outline.

From the docs, it seems I would be required to alter the exuberant ctags definition for every filetype where I wanted this functionality, as well as the tagbar definition.  Is there any way to support this directly within tagbar, at a general level?  So that it would work for any filetype, without requiring so much manual work to setup?

Because really, all that's needed is two things:
1. A regex that defines what a "comment section" is for a filetype.
2. A global tagbar option to turn the feature on/off.  Or a per-filetype config option.

**Comment by raven42** [comment]
This seems outside the scope of what tagbar currently does. Currently tagbar uses ctags output to generate a tree, but this would require tagbar to actually parse the file in question looking for a given regular expression, essentially generating it's own tags. Given all the different file types and possible ways a comment block could be formatted, it opens it up to too many possibilities. Unless there are no objections, given the age of this request and the fact that it is outside the scope of what tagbar is designed to do, and that nobody has taken this up for a possible PR, I would recomment this issue be closed.

**Comment by alerque** [comment]
As far as I know no `ctags` implementations output information about comment blocks. Since we don't do our own tag generation but rely on either generic (Universal Ctags) or language specific (Markdowntags, Gotags, etc.) tag generators, this is indeed outside our scope. If you want this feature the thing to do would be to get it added to something that generates tag maps, then it would become in scope for us to add the relevant output.
