### ISSUE TITLE
Custom tags cause errors

### ISSUE THREAD

**Issue by randy909** [preservim/tagbar#33]
Hi, This is both a bug report and a feature request. I'm passing flags to ctags to generate custom tags for a custom object system in perl like so:

```
--regex-perl=/^[ \t]*class[ \t]+([[:alnum:]:]+)/\1/k,classes,UR classes/
--regex-perl=/^[ \t]*([[:alnum:]_]+)[ \t]*=>[ \t]*\{/\1/r,properties,UR properties/
```

This is causing Tagbar to go nuts when it gets to the custom tags. Here are some of the errors i get:

```
Error detected while processing function <SNR>58_AutoUpdate..<SNR>58_ProcessFile..<SNR>58_parseTagline..393:
line 12:
E716: Key not present in Dictionary: k

Error detected while processing function <SNR>58_AutoUpdate..<SNR>58_ProcessFile..<SNR>58_parseTagline..393:
line 12:
E15: Invalid expression: fileinfo.kindfolds[self.fields.kind]

Error detected while processing function <SNR>58_AutoUpdate..<SNR>58_ProcessFile..419..<SNR>58_SortTags.. <SNR>58_CompareByKind:
line 3:
E716: Key not present in Dictionary: k
```

With Taglist I am able to add new categories to the view like this:

```
let tlist_perl_settings='perl;c:constant;l:label;p:package;k:class;r:property;s:subroutine'
```

So at a minimum it would seem good to have Tagbar ignore these extra tags when defined (or give a useful error message instead of exploding). Ideally it would support adding categories like Taglist.

Thanks for your awesome work,
Randy

**Comment by kberov** [comment]
@majutsushi , BTW It still gives the same error, but after putting the required variable in .vimrc it works fine.
Thanks!
