### ISSUE TITLE
Incorrect display sequence for "struct" and "enum" etc.

### ISSUE THREAD

**Issue by bearzyj** [preservim/tagbar#422]
Version: pull tagbar at 2017-06-24

Code sample:
```
#define DEF 2

typedef enum GHI{
    GHI_1,
    GHI_2
} ghi_e;

int MNO();
```

Then tagbar shows like this:
```
" Press <F1>, ? for help

▶ macros

▶ prototypes

▶-GHI : enum

▶ typedefs
```

Obviously, the "prototypes" tag should in bottom line. "struct" has the same problem.

**Comment by raven42** [comment]
The order the kinds show up in the tagbar window is not determined by the order they appear in the file. The order is dependent on the order of the dictionary for the `typeinfo.kinds` dictionary for the given file type. If you wish to change the order, then you can define your own definition for the `g:tagbar_type_<lang>` in your `.vimrc`.

For example:
```
	let g:tagbar_type_c = {
				\ 'ctagstype'	: 'c',
				\ 'kinds'		: [
					\ 'h:header files:1:0',
					\ 'd:macros:1:0',
					\ 'g:enums:0:1',
					\ 'e:enumerators:0:0',
					\ 't:typedefs:0:0',
					\ 's:structs:0:1',
					\ 'm:members:1:0',
					\ 'v:variables:0:0',
					\ 'f:functions:0:1',
					\ 'p:prototypes:1:0'
				\ ],
				\ 'sro'			: '::',
				\ 'kind2scope'	: {
					\ 'g' : 'enum',
					\ 's' : 'struct',
				\ },
				\ 'scope2kind'	: {
					\ 'enum'   : 'g',
					\ 'struct' : 's',
				\ }
			\ }
```
If you were to move the `prototypes` definition to the bottom like this, then it will appear last in the list.
