### ISSUE TITLE
High cpu usage when the cursor moves in tagbar window

### ISSUE THREAD

**Issue by vc60er** [preservim/tagbar#465]
High cpu usage when the cursor moves in tagbar window 

<img width="574" alt="wx20171215-154049 2x" src="https://user-images.githubusercontent.com/18476122/34031937-b9aa23f4-e1ae-11e7-965e-464345192c9d.png">

**Comment by majutsushi** [comment]
Tagbar doesn't really do anything itself when you are moving the cursor in its window. Off the top of my head I can only think of two things that may go on here:

- You have the `g:tagbar_autopreview` option set. In that case Tagbar installs a `CursorMoved` autocommand to always show the current tag in the preview window.
- You have the `updatetime` Vim option set to a very low value, in which case Tagbar will try to show the prototype of a tag very quickly. This is discouraged in both the Vim and Tagbar documentations.

If neither of these things is true then my only guess would be that a custom autocommand or another plugin is interfering. I would do some investigation with for example `:verbose autocmd CursorMoved` to try to figure out what's going on.

**Comment by vc60er** [comment]
Hi majutsushi, thank you for you reply. I found the problem. because i have set cursorline in my vimrc, it cause the high cpu usage, finally set nocursorline solved the problem.

**Comment by georgexsh** [comment]
@vc60er cool solved a longtime problem.

**Comment by georgexsh** [comment]
@majutsushi I would be nice if tagbar window could do `:set nocursorline` by default.

**Comment by raven42** [comment]
Closing this issue as per this comment. If there is still something needed here, please reopen.

> Hi majutsushi, thank you for you reply. I found the problem. because i have set cursorline in my vimrc, it cause the high cpu usage, finally set nocursorline solved the problem.
