### ISSUE TITLE
Disable current tag highlighting

### ISSUE THREAD

**Issue by virus-found** [preservim/tagbar#466]
I would like to disable current tag highlighting in the tagbar window to:
* improve performance on big files
* get rid of additional colouring

How do I do it?

**Comment by raven42** [comment]
To disable the highlighting you can use the following:
```vim
highlight default link TagbarHighlight Normal
```

Note: this doesn't stop the tag window from jumping to the current tag however.

To disable the auto update on large files, you can use the following introduced in #656 
```vim
let g:tagbar_file_size_limit = 10000  " Don't load tag for files larger than 10KB
```

Hopefully that works for your needs. If not, please feel free to reopen this issue with any more details for this request.
