### ISSUE TITLE
Variable displayed two times

### ISSUE THREAD

**Issue by chinleung** [preservim/tagbar#482]
I have a simple Laravel Class (app/User.php) and the Tagbar seems to be displaying a variable name two times.

```
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```

And in my Tagbar, I see:

```
> classes
    User

> variables
    fillable
    fillable
    hidden
    hidden
```

**Comment by nicolaiskogheim** [comment]
I can reproduce with the same file and `excuberant-ctags`.
`:h tagbar-issues` hints to run ctags manually. This is the output with the same file as above:

```sh
$ ctags -f - --format=2 --excmd=pattern --extra= --fields=nksaSmt user.php                                                                                 
User	user.php	/^class User extends Authenticatable$/;"	c	line:8
fillable	user.php	/^    protected $fillable = [$/;"	v	line:17
hidden	user.php	/^    protected $hidden = [$/;"	v	line:21
```

**Comment by raven42** [comment]
@nicolaiskogheim Are you still seeing this? I have tried with both Universal CTAGS and Exuberant CTAGS and I am not able to reproduce this.

**Comment by nicolaiskogheim** [comment]
Hi @raven42.
I cannot reproduce with Universal CTAGS anymore, no.
Didn't test exuberant ctags, because I didn't find it in my package manager.
Anyway, let's hear from @chinleung who reported the issue.

**Comment by alerque** [comment]
We're phasing ound support for the (unmaintained and antiquated) Exuberant Ctags. Given you used to have this problem with E and now don't have the problem with Universal Ctags which we do support, I think we can call this issue done. If anybody runs into this problem using a current version of U Ctags we'd be happy to have a new issue report for it.
