### ISSUE TITLE
Not listing tags

### ISSUE THREAD

**Issue by lai32290** [preservim/tagbar#485]
When I open tagbar by `:TagbarToggle`, it's not showing any tags, only message `No tags found.`

But I'm able to find tags by [fzf.vim](https://github.com/junegunn/fzf.vim), so I think the problem is not in 

Why my tags is not showing up?

**Comment by nicolaiskogheim** [comment]
Does `:TagbarToggle` work in any language at all?

**Comment by alerque** [comment]
What version of ctags, what language, and what version of vim are you using? This works for most of us so we're looking for something specifically messed up in your setup. We'll need more information to do that...

**Comment by raven42** [comment]
@lai32290 I am closing out this issue as it is more than 2 years old and there is not currently enough info to reproduce or to see what's going on. If you are still seeing an issue, please include some more info with code samples and ctags output so we can diagnose the issue better.
