### ISSUE TITLE
cursor moves slowly in tagbar window

### ISSUE THREAD

**Issue by JianCheng** [preservim/tagbar#49]
For a cpp or hpp file which has functions with many arguments, when I open the tagbar window, the cursor moves up or down slowly. If the functions has only a few arguments, the cursor moves fast. Different speed for different files annoys me.
Actually, even in the same file, the cursor in different area of the tagbar window moves in different speed, because different function has different number of arguments.
For taglist, the cursor moves in the same speed, because taglist does not show the arguments of functions. 
Hope the cursor in tagbar can also move in the same speed like taglist.

**Comment by vpshastry** [comment]
I hit the same problem and thanks for the answer @majutsushi.

But I prefer if we can enable cursorline without this performance drop. Isn't there any solution?

**Comment by majutsushi** [comment]
I don't think there's anything that can be done by Tagbar. This is a general issue with Vim's syntax highlighting speed.

**Comment by majutsushi** [comment]
I've made a small tweak to one of the syntax highlighting patterns that should hopefully speed things up a bit.

**Comment by vpshastry** [comment]
Is this the commit that addresses this issue?
https://github.com/majutsushi/tagbar/commit/7299257d7749ff2b31f134c9373d2324892e64d1

**Comment by majutsushi** [comment]
No, that's unrelated, there are no syntax changes in that commit. I mean the latest commit as of now.

**Comment by vpshastry** [comment]
That's great!! Much appreciated. :) Thanks.

**Comment by idning** [comment]
actually in my case it's the syntax rendering make cursor slow, when I disable tagbar/syntax/tagbar.vim file, it move super fast.

**Comment by elecalion** [comment]
> actually in my case it's the syntax rendering make cursor slow, when I disable tagbar/syntax/tagbar.vim file, it move super fast.
> 
> more specific, it's :
> 
> ```
>  execute "syntax match TagbarKind '" . s:pattern . "'"
> ```

Same problem, with `:syntime on`
``` 
TOTAL      COUNT  MATCH   SLOWEST     AVERAGE   NAME               PATTERN
  1.742623   1548   0       0.009308    0.001126  TagbarKind         \(^[+\-] \?\)\@3<=[^-+: ]\+[^:]\+$
  0.765896   1548   0       0.002235    0.000495  TagbarScope        \(\S\@<![+\-][-+# ]\?\)\@<=[^*(]\+\(\*\?\(([^)]\+)\)\? :\)\@=
  0.014148   2016   468     0.000054    0.000007  TagbarVisibilityPrivate \(\S\@<![+\- ]\)\@<=-\([^-+# ]\)\@=
  0.010868   2016   468     0.000037    0.000005  TagbarFoldIcon     \S\@<![+\-]\([-+# ]\?\)\@=
  0.009225   1548   0       0.000051    0.000006  TagbarVisibilityProtected \(\S\@<![+\- ]\)\@<=#\([^-+# ]\)\@=
  0.009120   1548   0       0.000040    0.000006  TagbarVisibilityPublic \(\S\@<![+\- ]\)\@<=+\([^-+# ]\)\@=
  0.009112   2016   2016    0.000025    0.000004  TagbarSignature    (.*)
  0.002242   1548   0       0.000022    0.000001  TagbarType          : \zs.*
  0.001479   1548   0       0.000007    0.000001  TagbarPseudoID     \*\ze :
  0.001195   1548   0       0.000005    0.000001  TagbarNestedKind   ^\s\+\[[^]]\+\]$
  0.000673   1548   0       0.000002    0.000000  TagbarHelp         ^".*

  2.566582   18432
```
