### ISSUE TITLE
Manually mark a pattern for tagbar to jump for specific filetype

### ISSUE THREAD

**Issue by ghost** [preservim/tagbar#503]
The use-case is that I have list of files in a folder that I can for example create a hidden file `.targod` to list markers for each file in that folder to be marked that I can trigger tarbar to read `.targod` and properly show candidates that have been marked for a specific file.

example: a `.conf` file that I mark `Issue`, and in `.targod` is something like:
```
filename.conf   Issue:
```
filename.conf
```
# Issue 1: this is important one to solve 1
...
# Issue 2: this is minor to solve 2
```
When I open `filename.conf` and trigger tagbar, list of candidates showing like below:
```
Issue 1: this is important one to solve 1
Issue 2: this is minor to solve 2
```

Is this possile with tagbar? Idon't find it in docs.

**Comment by raven42** [comment]
This seems like it would require a different custom plugin. Tagbar works in conjunction with ctags to provide a list of tags for the active file. This request doesn't seem to fit in with what the purpose of tagbar is designed for and would be better handled by a custom plugin specifically for that parsing. And what's more, tagbar uses the jump to jump to the location within the current file, not into other files. Closing this issue as it is not in the scope of tagbar.
