### ISSUE TITLE
New option: g:tagbar_jump_location

### ISSUE THREAD

**Issue by dpacbach** [preservim/tagbar#504]
Currently when one hits <CR> and jumps to a tag the tag is placed in the center of the editing window with the following command in tagbar.vim:

normal! z.

Instead, allow the user to override this behavior to allow e.g.:

let g:tagbar_jump_location = "+20"
let g:tagbar_jump_location = "-30"

Those would put the tag 20% above the center line, or 30% below the center line, respectively.

**Comment by alerque** [comment]
This would be an interesting feature to have. I've sometimes wished the jump would be to the top of the location instead of centered myself, making it configurable would be a nice touch.

@dpacbach would you be interested in contributing this change with a PR? If you are anybody is up for doing the work, the floor is open...

**Comment by dpacbach** [comment]
Another idea would be to have a flag that, if true, will cause tagbar not to scroll the window at all if the selected item is already visible in the window (it would just move the cursor).  Then if it's not visible in the window, then it would consult the `tagbar_jump_location` and jump/scroll to make it visible.

**Comment by yuriescl** [comment]
It would be nice to also have an option to always show the current tag at the center of the tagbar window. It's similar to this one but it would be applied to the tagbar window.

**Comment by alerque** [comment]
@yuriescl Could you please open that as a new issue? Even though the general idea is similar any implementation will be in a completely different part of the code so these should be tracked as two separate issues.
