### ISSUE TITLE
Tags returning function even when outside the scope

### ISSUE THREAD

**Issue by kkanungo17** [preservim/tagbar#516]
I use tagbar with lightline to show the function the cursor currently is in, which works fine, but when the cursor goes out of the scope but before going into another function, the previous function still stays.

This is correct:
![screen shot 2018-12-05 at 19 21 44](https://user-images.githubusercontent.com/11506039/49517828-15a13e00-f8c3-11e8-889a-f097cbb5dc6f.png)

This is not:
![screen shot 2018-12-05 at 19 21 52](https://user-images.githubusercontent.com/11506039/49517842-22be2d00-f8c3-11e8-99e7-4ecd9976d25d.png)

**Comment by bam80** [comment]
duplicate: #524 (also valid for Bash scripts)

Any progress here? Very  annoying..

**Comment by bam80** [comment]
@kkanungo17 FYI: you don't need any additional plugin to show the function in statusline.
I use following:
```
:let &statusline = '%f %([%{tagbar#currenttag(''%s'','''')}] %)%h%m%r%=%-14.(%l,%c%V%) %P'

**Comment by kkanungo17** [comment]
Thanks for the FYI, but I use lightline for a couple of other stuff and eye-candy as well. This issue is still annoying though.

**Comment by bam80** [comment]
@majutsushi any comments?

**Comment by bam80** [comment]
@kkanungo17, meanwhile, you are welcome to try https://github.com/dr-chip-vim-scripts/StlShowFunc.

It doesn't need neither tags nor any dependency plugins for it's functioning, does exactly the status line manipulation to show the name of the current function, and handles the scope correctly.

**Comment by alerque** [comment]
@bam80 and @kkanungo17 I would be happy to review a contribution if anybody wants to submit a PR that fixes this. I'm not entirely convinced it is a _bug_ so much as something you'd like configured differently, but if you can figure out how to make it work as expected and introduce that as on option I think that would be great. Keep in mind that in many languages there isn't an explicit closure at all, only opening a new heading/function/scope will close the previous one, so this might need some finesse not to break all languages.

**Comment by bam80** [comment]
> in many languages there isn't an explicit closure at all

In those cases there are indenting or such, am I missing something?
IMO it's clearly the bug since the feature is to show where you are and not what's the upper function name.

**Comment by alerque** [comment]
@bam80 Yes, you're missing something. For example Markdown and LaTeX are both languages for which there is no concept of ending one section except by starting another one. I'm sure there are others. I'm sure this plugin's behaviour can be improved for languages with explicit closures, feel free to have a stab at it. Just be aware of the different possible scenarios.

**Comment by bam80** [comment]
The question is if the scope can be addressed in ctags-like indexing programs. Probably GNU Global can do so
