### ISSUE TITLE
Add support for Crystal

### ISSUE THREAD

**Issue by duraki** [preservim/tagbar#517]

**Comment by alerque** [comment]
I would be happy to review a PR to add this support, but it is unlikely to get done by me, somebody who actually uses Crystal should consider contributing this.

**Comment by duraki** [comment]
I'm doing quite a bit of Crystal, although I'm not Vimscript dev. If someone can collab I'd gladly take a chance to contribute to any extent.

**Comment by alerque** [comment]
@duraki I don't think this will take very advanced vimscript skills to complete, familiarity with your target language is probably more important. I'm happy to walk you through the process too.

First up, does Universal Ctags even have support for Crystal? Can you run it manually on the command line and see if it gives you anything to work with? For example:

```sh
$ ctags -f - <inputfile>
```

...should spit out at least _something_ when given one of your Crystal files as input. Does it? If so all we have to do is figure out how those tags should map to the tree structure in tagbar, so basically we'll be creating a dictionary that maps those tags to our structure.

**Comment by dammer** [comment]
Hi @alerque, i am trying add support Crystal into tagbar through --regexp method, but tagbar open just blank window. In the tagbar debug log i see `Unsupported filetype: crystal`. I think this should work, vim is using the generated tags file normally. Please help me understand where i was wrong.
 
my ~/[.ctags](https://github.com/dammer/crystal-ctags/blob/45a81fa4260a7576dc725fe18b42f3c54e62cc10/.ctags)

vimrc tagbar config:
```vimrc
let g:tagbar_type_cr = {
            \ 'ctagstype' : 'Crystal',
            \ 'kinds'     : [
                \ 'd:defs',
                \ 'f:functions',
                \ 'm:macros',
                \ 'c:classes',
                \ 'm:modules',
                \ 'l:libs',
                \ 's:structs',
                \ 'a:aliases'
            \ ]
        \ }
```

`:TagbarGetTypeConfig cr` show:
```vim
let g:tagbar_type_cr = {
    \ 'kinds' : [
        \ 'd:defs',
        \ 'f:functions',
        \ 'm:macros',
        \ 'c:classes',
        \ 'm:modules',
        \ 'l:libs',
        \ 's:structs',
        \ 'a:aliases',
    \ ],
\ }
```

ctags has Crystal in list languages:
```bash
$ 'ctags-exuberant' --list-languages 
Ant
---skipped---
YACC
Crystal
```
[tagbardebug.log](https://github.com/preservim/tagbar/files/6911782/tagbardebug.log)

**Comment by dammer** [comment]
Ok, i fixed [that](https://github.com/preservim/tagbar/issues/517#issuecomment-890402157) just changing `g:tagbar_type_cr` on `g:tagbar_type_crystal`. This is little bit different from written in [documentation](https://github.com/preservim/tagbar/blob/a0a5714910d29ac3bfe91a2529a9c8cb28de77cc/doc/tagbar.txt#L1689) where `g:tagbar_type` named from file extension of added language. Anyway my vimrc: 
``` vim
let g:tagbar_type_crystal = {
            \ 'ctagstype' : 'Crystal',
            \ 'kinds'     : [
                \ 'd:defs',
                \ 'f:functions',
                \ 'm:macros',
                \ 'c:classes',
                \ 'm:modules',
                \ 'l:libs',
                \ 's:structs',
                \ 'a:aliases'
            \ ]
        \ }
```

**Comment by alerque** [comment]
If that setup is working for you and Universal Ctags supports this out of the box can we get that change as a PR to support it for everybody?

**Comment by dammer** [comment]
Course, i can make PR on weekend.
