### ISSUE TITLE
"Tag List" relation?

### ISSUE THREAD

**Issue by bam80** [preservim/tagbar#521]
Hi, thanks for the plugin.
I've never used Vim plugins much myself, just wondering if this plugin is something related to [Tag List](http://vim-taglist.sourceforge.net/index.html) ("the top-rated and most-downloaded plugin for the Vim editor").
Would love to see first-look comparison of both.
Thanks!

**Comment by raven42** [comment]
Yes this plugin looks to be very similar to [Tag List](https://github.com/yegappan/taglist). As for a feature comparison, I think that would be best served by trying them both out. I have only used tagbar so I'm not familiar with Tag List and so I can't speak to that. It does look like both provide similar functionality though. At a quick glance, the only thing that Tag List provides that tagbar does not is adding tags for all open files and grouping them accordingly, where tagbar just does the active file/buffer and updates the tagbar window every time the buffer is switched.
