### ISSUE TITLE
tagbar error with sh files

### ISSUE THREAD

**Issue by riteshharjani** [preservim/tagbar#547]
I keep getting below error with filetype=sh.
Any idea??

```
Error detected while processing function <SNR>80_AutoUpdate[63]..<SNR>80_ProcessFile[119]..<SNR>84_sortTags[2]..tagbar#sorting#sort[6]..<SNR>88_compare_by_kind:
line    3:
E716: Key not present in Dictionary: v
```

**Comment by alerque** [comment]
I am not able to replicate this. Are you sure it happens on all `sh` files? What version of ctags are you using? Have you tried a Universal Ctags release?

**Comment by ccaprani** [comment]
I have replicated through the following file:
1. Go to [https://bayessm.org/](https://bayessm.org/)
2. Download the Beamer slides at the bottom
3. Chapter 1 - `intro.tex`
4. Observe bug.

**Comment by alerque** [comment]
@ccaprani This bug report is about SH files. There are no SH files in that zip of beamer slides. Your steps suggest you are opening a TEX file which is different. I did try opening various tex files there too, but do not see any issues, I don't get a similar error.
