### ISSUE TITLE
Add option for tagbar tag position in the window

### ISSUE THREAD

**Issue by yuriescl** [preservim/tagbar#564]
Add option to control where the current tag is positioned in the tagbar window.
It would allow, for example, to always keep the current tag at the center/top/bottom of the tagbar window.
This option is similar to the one proposed [here](https://github.com/majutsushi/tagbar/issues/504), but applies to the tagbar window.

**Comment by raven42** [comment]
This could be handled by enabling `setlocal scrolloff=10` to the tagbar window. Or if you set it to a large value, then it should always keep the highlighted tag centered.

**Comment by yuriescl** [comment]
Thanks!
