### ISSUE TITLE
Question for cpp: how to not fold macro (or everything) be default?

### ISSUE THREAD

**Issue by 9527KGG** [preservim/tagbar#592]
This is what it looks like by default:

![image](https://user-images.githubusercontent.com/12282281/73971809-73208880-48d4-11ea-8e16-bf0f4ec2fb79.png)

How to not fold macro (or everything) be default?

Thanks.

**Comment by raven42** [comment]
@9527KGG You can override the default settings for a given tag file type. If you look at [doc/tagbar.txt](../doc/tagbar.txt) in the `6. Extending Tagbar` section, there is a discussion for how to do this. The part  you will want to change is the `'kinds' : [ ... 'd:macros:1:0' ... ]` to set the `fold` parameter (third field) to `0` so it won't fold by default.

**Comment by 9527KGG** [comment]
Thanks. Working now.
