### ISSUE TITLE
How can I hide the tag types (e.g. class, function) for Python tags?

### ISSUE THREAD

**Issue by danijar** [preservim/tagbar#600]
Tagbar is displaying tags for Python code like this:

```
MyClass : class
  __init__ : function
  my_method : function
```

How can I remove the tag types and show only names?

```
MyClass
  __init__
  my_method
```

Thanks!

**Comment by raven42** [comment]
@danijar You can override the defaults for the python file type by defining your own python tag type. If you look at [doc/tagbar.txt](../doc/tagbar.txt) in the `6. Extending Tagbar` section, there is an explanation of how to do this. To remove the 'function' and 'class' identifiers after the name, you can remove the entries from the kind2scope and scope2kind mapping. The following should do what you want:
```
let g:tagbar_type_python = {
			\ 'ctagstype'	: 'python',
			\ 'kinds'		: [
				\ 'i:modules:1:0',
				\ 'c:classes:0:1',
				\ 'f:functions:0:1',
				\ 'm:members:0:1',
				\ 'v:variables:0:0'
			\ ],
			\ 'sro'			: '.',
			\ 'kind2scope'	: { },
			\ 'scope2kind'	: { }
		\ }
```

**Comment by raven42** [comment]
@danijar will the above work for your needs? or are you looking for a little more?

**Comment by alerque** [comment]
I'm pretty sure this is the solution; @danijar feel free to holler if this doesn't accomplish the job.
