### ISSUE TITLE
How can I only show classes and functions?

### ISSUE THREAD

**Issue by danijar** [preservim/tagbar#601]
Right now, tagbar also shows import statements and other categories of tags. Is is possible to hide them and only show classes and functions?

**Comment by raven42** [comment]
You can override any default tag types for a given file type. If you look in the [doc/tagbar.txt](../doc/tagbar.txt) file in the `6. Extending Tagbar` section, there is a discussion about how to change the tag types that are examined. This includes an example for cpp files. If you want to show only a couple types, then you could change it to the following:
```
let g:tagbar_type_cpp = {
            \ 'ctagstype' : 'c++',
            \ 'kinds'     : [
                \ 'c:classes',
                \ 'f:functions',
            \ ],
            \ 'sro'        : '::',
            \ 'kind2scope' : {
                \ 'c' : 'class',
            \ },
            \ 'scope2kind' : {
                \ 'class'     : 'c',
            \ }
        \ }
```

There are other file types as well that you could take the defaults from and modify accordingly in your `.vimrc` located at [autoload/tagbar/types](../autoload/tagbar/types).

Will this work for your purposes?

**Comment by raven42** [comment]
Closing this issue. With the correct `g:tagbar_type_XXX` definition, it is possible to limit the output as indicated above. If further help is still needed, please let us know.
