### ISSUE TITLE
C functions with union inside of them show up with expand/fold arrow

### ISSUE THREAD

**Issue by raven42** [preservim/tagbar#637]
I'm working with some C code that has some unions defined in the variables. When tagbar is loaded, it is showing an expansion arrow next to the function name which includes the union as if it can be folded. Is there a way to fix this so it shows up like all the other functions?

When clicking on the arrow next to the function, the fold for the 'Functions' block is activated causing all functions to be hidden.

Here is a screenshot of an example. In function3() you can see a union in the variable declarations, and then the green fold/expansion arrow is seen next to function3() in the tagbar window:
![image](https://user-images.githubusercontent.com/3730811/89454386-42f06000-d726-11ea-9a99-5a827b9fe404.png)

**Comment by alerque** [comment]
I don't work with C much, but I imagine there is a way to setup your config to avoid this. For best chance of a response form somebody who wants to mess with it you should probably post an actual C code sample, screen shots are hard to copy/paste from.

**Comment by raven42** [comment]
Here is the example code I gave.
```
/*
 * Test file for generic use
 */

#include <stdio.h>

int funtion1(int i) {
	return (0);
}

int funtion2(int i) {
	return (0);
}

int funtion3(int i) {
	union {
		char buf1[10];
		int int1;
	} var;

	return (0);
}

int funtion4(int i) {
	return (0);
}

int main(int argc, char *argv[]) {
	printf("all your base are belong to us\n");

	return (0);
}
```

**Comment by raven42** [comment]
Managed to look into this a little bit. Noticed another odd behavioral thing with this as well. If I move the cursor inside of `function3()` in the example code, but after the union `var`, then the highlighted variable in the tagbar window stays on the union instead of reverting to `function3()`. This also affects the `tagbar#currenttag()` routine as well if used in the status line or similar where it will display the union instead.

This is behavior is likely being caused by the scoping of tagbar where it is looking for the closest tag up from the current line, and doesn't actually recognize scope.

As a workaround I set my own `g:tagbar_type:c` and removed the union from the list of types to execute tags on and that seems to work for my liking. I will close out this issue with this workaround. Here is the addition to my `.vimrc` for documentation purposes:
```
	let g:tagbar_type_c = {
		\ 'ctagstype'	: 'c',
		\ 'kinds'		: [
			\ 'h:header files:1:0',
			\ 'd:macros:1:0',
			\ 'p:prototypes:1:0',
			\ 'g:enums:0:1',
			\ 'e:enumerators:0:0',
			\ 't:typedefs:0:0',
			\ 's:structs:0:1',
			\ 'm:members:0:0',
			\ 'v:variables:0:0',
			\ 'f:functions:0:1'
		\ ],
		\ 'sro'			: '::',
		\ 'kind2scope'	: {
			\ 'g' : 'enum',
			\ 's' : 'struct',
		\ },
		\ 'scope2kind'	: {
			\ 'enum'   : 'g',
			\ 'struct' : 's',
		\ }
	\ }
```
Note: This will disable any tag generation in the tagbar window for all unions, so if you don't need that you can use this workaround.
