### ISSUE TITLE
Tagbar error when opening tex file

### ISSUE THREAD

**Issue by petobens** [preservim/tagbar#654]
See https://github.com/vim-airline/vim-airline/issues/2226

**Comment by alerque** [comment]
Does tagbar work otherwise? Can you pull up the tag pane any everything is fresh?

**Comment by petobens** [comment]
Hi @alerque . If I run `:Tagbar` on:
```tex
\documentclass{beamer}

\begin{document}

\begin{frame}
  \frametitle{Foo}
\end{frame}

\end{document}
```

I get
```
Unknown tag kind encountered: "f". Your ctags and Tagbar configurations are out of sync! Please read ':help tagbar-extend'.
```
Adding the following seems to fix it:
```let g:tagbar_type_tex = {
    \ 'kinds' : [
        \ 'f:frames'
    \ ]
\ }
```

**Comment by alerque** [comment]
What version of `ctags` are you using?

**Comment by petobens** [comment]
Latest master:
```
Universal Ctags 0.0.0(96237bce1), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Sep  8 2020, 13:05:20
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc
```

**Comment by alerque** [comment]
I believe #676 probably fixed the *error message*, and manually defining the types for TeX might have gotten you frames is your tagbar, but I see one thing here that isn't covered: TeX frame tags aren't showing up it tagbar out of the box. I'm re-opening this to track that as the final resolution.
