### ISSUE TITLE
what happened the repo's url ?

### ISSUE THREAD

**Issue by Shane-XB-Qian** [preservim/tagbar#655]
maybe silly, but want to confirm tagbar 's repo had been transfer-ed or mirror-ed 
from : `remote.origin.url=https://github.com/majutsushi/tagbar.git` to here ?
though the url still under 'majutsushi' at my local, (so need confirm if needed to update) but redirect to here automaticly now ..
the ori owner transfer-ed the repo ?

**Comment by alerque** [comment]
Yes. See #651.

**Comment by Shane-XB-Qian** [comment]
ok, thanks your confirm, and i am reading #651 .
just may/would be a little confusion/mess, since looks no way to detect the ownership change from the git config or sth at local, except the url redirection.

**Comment by alerque** [comment]
> except the url redirection

This is exactly what redirection is for. The status code & redirect is literally a way of saying "This thing you were looking for on this URL has now moved, the canonical location is now some other place, I'm forwarding you over there." — it makes things continue to work seamlessly (not actually breaking the old URLs) while making sure as often as possible people end up on the new URLs. I don't know what else you expect to have happen.

**Comment by Shane-XB-Qian** [comment]
well, sometime unless the ori owner confirmed, otherwise user maybe concerned the redirection was a security risk fake.
at least to me .. :) since looks no way to detect the change from git config or sth at local .. 
at least, user maybe confused or hesitated if really need to update the url (e.g at plugin mgr) or had to ..

**Comment by alerque** [comment]
In the case of Github transferring repositories can only be initiated by repository owners. If the original owner didn't confirm the migration there wouldn't be redirects in the first place! That or the original owner's account is completely compromised, in which case you wouldn't be able to get trustworthy confirmation anyway—and the repository could be compromised in other ways without you noticing.

**Comment by Shane-XB-Qian** [comment]
i see, but redirection did not always mean repo owner 's password had been hacked, but just the url ..
anyway, that just a concern or confusion (to me at least or only, perhaps), or a strange feeling.
but since this had been confirmed, and had done, then let it be. thanks your answer.

**Comment by Shane-XB-Qian** [comment]
btw: you are doing a great job - i am a little worry some classic wonderful vim plugin lost update too  :)
but moved all those repo into one account not sure if was a good idea, since/looks there was a `vim-scripts` account too - lots classic plugins from vim.org, but looks no update anymore.
another hand even though, not sure if git or github side later can feedback a redirection confirmation msg after clone/pull cmd, that maybe a little convinced/helpful to user. 
fyi.

**Comment by alerque** [comment]
The @vim-scripts org was just scraping plugin sources from other sites (notably vim.org), there was no effort at maintaining them there. Everything in there should be considered a fork (or ignored).

Note that this effort is **not** pulling everything under one account. This is an *organization* namespace and has multiple people listed an owners and many more members with permissions on the projects they contribute to. Every one of the projects here has multiple admins and contributors. The idea is to diversify and spread out the responsibility, not to put it under one person.

I'd be happy to talk to other great classic plugins that are struggling but there are some qualifications. I'm not interested in loading up on a bunch of plugins that nobody is interested in maintaining, only in freeing up projects that are no longer primarily maintained by their original authors. There needs to be at least one active maintainer who is also willing to work with other collaborators, and the plugin has to be reasonable successful (say 1k stars or something). There are undoubtedly some other good ones out there that have lots of open PRs from active users, the original author is not actively working on, and somebody would be interested maintaining that we could consider—but this is a limited subset of all the classic plugins that have fallen by the wayside.

**Comment by Shane-XB-Qian** [comment]
um.. looks like a biz mode - a some kind foundation.
whatever, i just wish some plugin e.g `dbext` would not dead ..
