### ISSUE TITLE
Errors with g:tagbar_visibility_symbols

### ISSUE THREAD

**Issue by chronon** [preservim/tagbar#662]
It looks recent changes per #660 broke things for me with NVIM v0.4.4:

![Screen Shot 2020-09-23 at 9 52 23 AM](https://user-images.githubusercontent.com/57735/94022205-d6d3c500-fd82-11ea-92fe-cc53b7aa112a.jpg)

**Comment by alerque** [comment]
Oops! And if I'd finished #616 it would have caught this too.

**Comment by chronon** [comment]
Fix confirmed, thanks for taking care of that so quickly!
