### ISSUE TITLE
Autoclosing won't close preview window

### ISSUE THREAD

**Issue by tanchihpin0517** [preservim/tagbar#670]
While I set auto-close on and jump to a certain tag, the main tag window is closed automatically but the preview window still remains.
I'm not sure whether it's a bug or just a normal routine.

Here is my settings about tagbar:
let g:tagbar_width = 30    
let g:tagbar_sort = 0    
let g:tagbar_autoclose = 1    
let g:tagbar_autofocus = 1    
let g:tagbar_compact = 1
let g:tagbar_autopreview = 1
let g:tagbar_map_showproto = "d"                                                                                                                                      
let g:tagbar_previewwin_pos = "rightbelow"

**Comment by raven42** [comment]
This is the same as the first part of #624. We can track this under that issue.
