### ISSUE TITLE
how to set number   in tagbar?

### ISSUE THREAD

**Issue by jingkai1** [preservim/tagbar#671]
how to set number   in tagbar.  I wish to see the line number.

**Comment by alerque** [comment]
The line number of what? The tagbar buffer? Or of the tags in the target file?

**Comment by jingkai1** [comment]
![Uploading 2020-10-05 13-50-16屏幕截图.png…]()

**Comment by jingkai1** [comment]
tagbar buffer

**Comment by jingkai1** [comment]
![2020-10-05 13-51-24屏幕截图](https://user-images.githubusercontent.com/68280301/95044391-e273a400-0711-11eb-8e76-7d947807e97b.png)

**Comment by jingkai1** [comment]
I wish see number when file open.

**Comment by raven42** [comment]
This can be set with the `g:tagbar_show_linenumbers` option.
