### ISSUE TITLE
Problems opening perl files

### ISSUE THREAD

**Issue by diegok** [preservim/tagbar#672]
Since I've updated around a month ago I'm having lots of errors opening perl files and probably others:

```
Error detected while processing function tagbar#ToggleWindow[2]..<SNR>90_ToggleWindow[9]..<SNR>90_OpenWindow[81]..<SNR>90_AutoU
pdate[63]..<SNR>90_ProcessFile[146]..<SNR>110_sortTags[2]..tagbar#sorting#sort[6]..<SNR>114_compare_by_kind:
line    3:
E716: Key not present in Dictionary: m
E15: Invalid expression: typeinfo.kinddict[a:tag1.fields.kind] <# typeinfo.kinddict[a:tag2.fields.kind]
E716: Key not present in Dictionary: m
```

I had to disable this plugin as it was impossible to work with it and I was updating and re-checking since this problems started. I've seen other issues with similar problems for JS/bash so I was just waiting to see how it goes but I don't see any progress. I'm using universal-ctags and I've seen in those issues that this can be related, but it doesn't exists a package for the old "exuberant-ctags" on my distro...

If there is any more info I can collect to help understand this problem just let me know.

**Comment by raven42** [comment]
Do you have a sample perl script that generates this error? I only have a few small perl scripts and I do not see this error when I open them up.

**Comment by diegok** [comment]
Sure, I've just reproduced this problem here:

- https://github.com/diegok/resque-perl/blob/master/lib/Resque/Job.pm

**Comment by raven42** [comment]
I have a potential fix to address this globally for unknown `kinds`. I am not sure what the specifics of the perl `m` kind is, so #676 will not actually add proper handling for the `m` kind, but only prevent any tagbar failures when an unknown kind is found.

As a followup for this, someone more familiar with perl can update the perl type definition to include the proper `m` kind (and possibly the `a` kind too).

**Comment by diegok** [comment]
Hey @raven42 I can help out with this. I'm not familiar with ctags or vim script, but I'm all in to help improve this.

From what you've said and what I've pasted, `m` looks like `method` as in: `fail	lib/Resque/Job.pm	/^sub fail {$/;"	m	class:Resque::Job` but then I can see an `s` with the same line but without the class at the end, so I'm probably missing something here :-/

On the other hand the `a` looks like `attribute` which is what `has` is used for. To give you some more context, this is nos native perl but an convention provided by several libraries in CPAN which Moose is the most used and the one used by this example.

Just let me know if I can help in any other way and thank you!.

**Comment by diegok** [comment]
On your PR you've said:

> This is occurring because there are unknown kinds found when running ctags. This results in a dictionary lookup because the perl type isn't handling these other kinds

Do you think I can improve the "perl type"?, where should I look to do so?

**Comment by diegok** [comment]
Ok, I answer myself:

- https://github.com/preservim/tagbar/blob/55f3513d10cd93153777f5eb3be902a9b95c6be9/autoload/tagbar/types/uctags.vim#L717

I'll play around it :+1:

**Comment by diegok** [comment]
Done: https://github.com/preservim/tagbar/pull/677 :+1:
