### ISSUE TITLE
More granular `g:tagbar_compact`

### ISSUE THREAD

**Issue by maujim** [preservim/tagbar#673]
Currently, setting `g:tagbar_compact = 1` will disable the short help message at the top and remove spaces between top-level scopes. Is there a way to only disable the help message and keep the spacing between scopes?

I'm happy to work on this as a feature if there's no other way to do it in the plugin currently.

**Comment by raven42** [comment]
Currently no there is no option for this. If you want to work on it that would be most welcome. I'd recommend adding a new value for the existing option like:
```vim
let g:tagbar_compact = 2   " No help message, but still separation between scopes
```

**Comment by maujim** [comment]
Excellent that's exactly how I was thinking of structuring it. I will work on this over the weekend
