### ISSUE TITLE
show type of field by default 

### ISSUE THREAD

**Issue by ssh352** [preservim/tagbar#680]
by pressing space key, the user can see the full prototype of field and methods, is it possible for tag bar to show the full prototype by default without the user pressing space? Thank you

**Comment by alerque** [comment]
I can't make out what exactly you want to happen here. By pressing what: `l`? where? when the cursor is on what? And what exactly do you see? Maybe a screen capture showing the output you are thinking of would be useful. And what language are you working with?

**Comment by ssh352** [comment]
<img width="634" alt="Screen Shot 2020-10-23 at 10 12 41 AM" src="https://user-images.githubusercontent.com/41779116/96948477-54245e00-1518-11eb-81a7-06d498fcebf8.png">

sorry I edited the post. Basically is it possible to have the types of the fields, and the full signature of methods shown in tagbar?

**Comment by raven42** [comment]
@ssh352 can you please include a sample of a source file and the the language so we can look into this more?

**Comment by ssh352** [comment]
@raven42 sure,  https://github.com/real-logic/aeron/blob/d572ee5735435026c3b461ded410519cbcc6be63/aeron-driver/src/main/java/io/aeron/driver/Configuration.java

**Comment by raven42** [comment]
Thanks. So just so I understand the request (sorry... not really familiar with Java), the full signature I see for your example looks like this:
```
public static final long CLIENT_LIVENESS_TIMEOUT_DEFAULT_IS = TimeUnit.SECONDS.toNanos(10);
```
And the corresponding ctags output is as follows:
```
CLIENT_LIVENESS_TIMEOUT_DEFAULT_NS	test.java	/^    public static final long CLIENT_LIVENESS_TIMEOUT_DEFAULT_NS = TimeUnit.SECONDS.toNanos(10);$/;"	f	line:290	class:Configuration	access:public
```

Now, for this request, are you asking that the full signature `public static final long CLIENT_LIVENESS_TIMEOUT_DEFAULT_IS = TimeUnit.SECONDS.toNanos(10);` be shown in the tagbar window?

**Comment by ssh352** [comment]
Correct. It would be nice to have an option have tagbar show the type of fields just like an IDE does, and the return type of methods and their parameter types, be it C++ or Java. 

Here is an example from Clion on a c++ source file. Having the type info in tagbar would be nice.


<img width="807" alt="Screen Shot 2020-10-30 at 9 57 22 AM" src="https://user-images.githubusercontent.com/41779116/97651271-90b30500-1a96-11eb-9c92-645512363698.png">

**Comment by raven42** [comment]
Ok, so looked into this a bit. There isn't always guaranteed to be enough data provided by ctags to get the full data type. We can try to assume the data type based on the pattern that ctags returns, but this only works if the data type is on the same line as the tag that was found.

For example - this will work:
```c
int some_function(int arg1) {
   ...
}
```
But this will not:
```c
int
some_function(int arg1)
{
   ...
}
```

Both are valid syntax, but in the second case, ctags only returns the pattern `some_function(int arg1)` and so we have no way to derive the data type. So that said, I have an attempt at this in this patch. Note: this also contains a small change to strip off the declaration after the tag when setting up the prototype (I.E. `int some_var` instead of `int some_var = 42`):

<details>
<summary>Click to show data-type patch</summary>

```diff
diff --git a/autoload/tagbar/prototypes/basetag.vim b/autoload/tagbar/prototypes/basetag.vim
index d002afa..ce04a20 100644
--- a/autoload/tagbar/prototypes/basetag.vim
+++ b/autoload/tagbar/prototypes/basetag.vim
@@ -15,6 +15,7 @@ function! tagbar#prototypes#basetag#new(name) abort
     let newobj.fields.line   = 0
     let newobj.fields.column = 0
     let newobj.prototype     = ''
+    let newobj.data_type     = ''
     let newobj.path          = ''
     let newobj.fullpath      = a:name
     let newobj.depth         = 0
@@ -30,6 +31,7 @@ function! tagbar#prototypes#basetag#new(name) abort
     let newobj.isSplitTag = function(s:add_snr('s:isSplitTag'))
     let newobj.isKindheader = function(s:add_snr('s:isKindheader'))
     let newobj.getPrototype = function(s:add_snr('s:getPrototype'))
+    let newobj.getDataType = function(s:add_snr('s:getDataType'))
     let newobj._getPrefix = function(s:add_snr('s:_getPrefix'))
     let newobj.initFoldState = function(s:add_snr('s:initFoldState'))
     let newobj.getClosedParentTline = function(s:add_snr('s:getClosedParentTline'))
@@ -72,6 +74,11 @@ function! s:getPrototype(short) abort dict
     return self.prototype
 endfunction
 
+" s:getDataType() {{{1
+function! s:getDataType() abort dict
+    return self.data_type
+endfunction
+
 " s:_getPrefix() {{{1
 function! s:_getPrefix() abort dict
     let fileinfo = self.fileinfo
diff --git a/autoload/tagbar/prototypes/normaltag.vim b/autoload/tagbar/prototypes/normaltag.vim
index c3ba1f7..3c127e5 100644
--- a/autoload/tagbar/prototypes/normaltag.vim
+++ b/autoload/tagbar/prototypes/normaltag.vim
@@ -14,6 +14,7 @@ function! tagbar#prototypes#normaltag#new(name) abort
     let newobj.strfmt = function(s:add_snr('s:strfmt'))
     let newobj.str = function(s:add_snr('s:str'))
     let newobj.getPrototype = function(s:add_snr('s:getPrototype'))
+    let newobj.getDataType = function(s:add_snr('s:getDataType'))
 
     return newobj
 endfunction
@@ -36,6 +37,10 @@ function! s:strfmt() abort dict
     endif
     let prefix = self._getPrefix()
 
+    if g:tagbar_show_data_type && self.getDataType() !=# ''
+        let suffix .= ' : ' . self.getDataType()
+    endif
+
     if g:tagbar_show_tag_linenumbers == 1
         let suffix .= ' [' . self.fields.line . ']'
     elseif g:tagbar_show_tag_linenumbers == 2
@@ -78,6 +83,8 @@ function! s:getPrototype(short) abort dict
         endif
 
         let line = getbufline(bufnr, self.fields.line)[0]
+        " If prototype includes declaration, remove the '=' and anything after
+        let line = substitute(line, '\s*=.*', '', '')
         let list = split(line, '\zs')
 
         let start = index(list, '(')
@@ -124,6 +131,37 @@ function! s:getPrototype(short) abort dict
     return prototype
 endfunction
 
+" s:getDataType() {{{1
+function! s:getDataType() abort dict
+    if self.data_type !=# ''
+        let data_type = self.data_type
+    else
+        let bufnr = self.fileinfo.bufnr
+
+        if self.fields.line == 0 || !bufloaded(bufnr)
+            " No linenumber available or buffer not loaded (probably due to
+            " 'nohidden'), try the pattern instead
+            return substitute(self.pattern, '^\\M\\^\\C\s*\(.*\)\\$$', '\1', '')
+        endif
+
+        let line = getbufline(bufnr, self.fields.line)[0]
+        let data_type = substitute(line, '\s*' . self.name . '.*', '', '')
+
+        " Strip off the path if we have one along with any spaces prior to the
+        " path
+        if self.path !=# ''
+            let data_type = substitute(data_type, '\s*' . self.path . self.typeinfo.sro, '', '')
+        endif
+
+        " Strip off leading spaces
+        let data_type = substitute(data_type, '^\s\+', '', '')
+
+        let self.data_type = data_type
+    endif
+
+    return data_type
+endfunction
+
 " s:add_snr() {{{1
 function! s:add_snr(funcname) abort
     if !exists('s:snr')
diff --git a/plugin/tagbar.vim b/plugin/tagbar.vim
index 08f05d3..4bbf9d5 100644
--- a/plugin/tagbar.vim
+++ b/plugin/tagbar.vim
@@ -104,6 +104,7 @@ function! s:setup_options() abort
         \ ['scopestrs', {}],
         \ ['scrolloff', 0],
         \ ['show_balloon', 1],
+        \ ['show_data_type', 0],
         \ ['show_visibility', 1],
         \ ['show_linenumbers', 0],
         \ ['show_tag_count', 0],
```
</details>

We can turn this into a PR, but I think we might need more input from users of other languages to see if this will be correct for all/most languages.

**Comment by raven42** [comment]
So did a little more digging on this, and there is a `--fields=t` option for universal ctags that will show the data type for a tag. Unfortunately, this doesn't appear to work for the java file you sent me. That field was not printed when looking at that java file. So maybe we can do a mix of the two? If the `typedef` field is found, we use that, else we try to guess using something similar to the patch above.

**Comment by raven42** [comment]
I've pushed up a draft PR for this... it should have more language testing before we merge it in.
