### ISSUE TITLE
New Option: g:tagbar_jump_lazy_scroll

### ISSUE THREAD

**Issue by dpacbach** [preservim/tagbar#703]
Currently when jumping to a tag, the buffer will always be scrolled to place the tag at the location dictated by `g:tagbar_jump_offset`.  This means that if I jump to a tag that is already visible in the window (say, a few lines below my cursor) then the window will be scrolled unnecessarily, which can be a bit disorienting.

Solution: have a new option called `g:tagbar_jump_lazy_scroll` (defaults to `0`) which, when turned on, will cause the following jump behavior:

  1. If the tag being jumped to is already visible in the window then just put the cursor on that line without scrolling the window.
  2. If the tag is not visible in the window, then perform the current jumping/scrolling behavior whereby the buffer is scrolled to put the tag/cursor on the line dictated by `g:tagbar_jump_offset`.

I think this would make for a smoother and more intuitive user experience.

**Comment by raven42** [comment]
That seems like a good idea. I'm not sure how best to implement something like this though. Are there any vim options to do this?

**Comment by dpacbach** [comment]
I will submit a PR shortly.
