### ISSUE TITLE
regression issue started from pr #683

### ISSUE THREAD

**Issue by Shane-XB-Qian** [preservim/tagbar#708]
@raven42  there is a regression issue started from pr #683 : tag highlight does not work Unless cursor on that func name same line.
![image](https://user-images.githubusercontent.com/13550529/98819971-80bcfd00-2468-11eb-9147-38d28596078a.png)
// so far not sure which piece caused this, but looks started from this pr.
// could you check to refine the logic, or revert, or had a option to disable it ? thx.

**Comment by Shane-XB-Qian** [comment]
![image](https://user-images.githubusercontent.com/13550529/98820789-9bdc3c80-2469-11eb-9b55-276e8a426941.png)

**Comment by Shane-XB-Qian** [comment]
```diff
diff --git a/autoload/tagbar.vim b/autoload/tagbar.vim
index 0e699e4..4f7b890 100644
--- a/autoload/tagbar.vim
+++ b/autoload/tagbar.vim
@@ -1767,9 +1767,7 @@ function! s:create_pseudotag(name, parent, kind, typeinfo, fileinfo) abort
                     \ pseudotag.path . a:typeinfo.sro . pseudotag.name
     endif
     let pseudotag.depth = len(split(pseudotag.path, '\V' . escape(a:typeinfo.sro, '\')))
-
     let pseudotag.parent = a:parent
-
     let pseudotag.fileinfo = a:fileinfo
     let pseudotag.typeinfo = a:typeinfo
 
@@ -1985,7 +1983,6 @@ function! s:PrintKinds(typeinfo, fileinfo) abort
                     let curline                   = len(output) + offset
                     let tag.tline                 = curline
                     let a:fileinfo.tline[curline] = tag
-                    let tag.depth                 = 1
                 endfor
             endif
 
@@ -2136,9 +2133,9 @@ function! s:HighlightTag(openfolds, ...) abort
     let force = a:0 > 0 ? a:1 : 0
 
     if a:0 > 1
-        let tag = s:GetNearbyTag(1, 0, a:2)
+        let tag = s:GetNearbyTag('highlight', 0, a:2)
     else
-        let tag = s:GetNearbyTag(1, 0)
+        let tag = s:GetNearbyTag('highlight', 0)
     endif
     if !empty(tag)
         let tagline = tag.tline
@@ -2576,7 +2573,7 @@ function! s:OpenParents(...) abort
     if a:0 == 1
         let tag = a:1
     else
-        let tag = s:GetNearbyTag(1, 0)
+        let tag = s:GetNearbyTag('parent', 0)
     endif
 
     if !empty(tag)
@@ -2993,7 +2990,7 @@ endfunction
 
 " s:GetNearbyTag() {{{2
 " Get the tag info for a file near the cursor in the current file
-function! s:GetNearbyTag(all, forcecurrent, ...) abort
+function! s:GetNearbyTag(request, forcecurrent, ...) abort
     if s:nearby_disabled
         return {}
     endif
@@ -3019,7 +3016,19 @@ function! s:GetNearbyTag(all, forcecurrent, ...) abort
     for line in range(curline, 1, -1)
         if has_key(fileinfo.fline, line)
             let curtag = fileinfo.fline[line]
-            if a:all || typeinfo.getKind(curtag.fields.kind).stl
+            if a:request ==# 'highlight' && typeinfo.getKind(curtag.fields.kind).stl
+                let tag = curtag
+                break
+            endif
+            if a:request ==# 'highlight' && line == curline
+                let tag = curtag
+                break
+            endif
+            if a:request ==# 'statusline' && typeinfo.getKind(curtag.fields.kind).stl
+                let tag = curtag
+                break
+            endif
+            if a:request ==# 'parent'
                 let tag = curtag
                 break
             endif
@@ -3548,7 +3557,7 @@ function! tagbar#GetTagNearLine(lnum, ...) abort
         let prototype = 0
     endif
 
-    let taginfo = s:GetNearbyTag(0, 1, a:lnum)
+    let taginfo = s:GetNearbyTag('statusline', 1, a:lnum)
 
     if empty(taginfo)
         return ''
@@ -3689,7 +3698,7 @@ function! tagbar#currenttag(fmt, default, ...) abort
         return a:default
     endif
 
-    let tag = s:GetNearbyTag(0, 1)
+    let tag = s:GetNearbyTag('statusline', 1)
 
     if !empty(tag)
         if prototype
@@ -3761,7 +3770,7 @@ function! tagbar#currenttagtype(fmt, default) abort
     " the CloseWindow() function from removing the autocommands.
     let s:statusline_in_use = 1
     let kind = ''
-    let tag = s:GetNearbyTag(0, 1)
+    let tag = s:GetNearbyTag('statusline', 1)
 
     if empty(tag)
         return a:default
@@ -3782,5 +3791,36 @@ function! tagbar#currenttagtype(fmt, default) abort
     return printf(a:fmt, singular)
 endfunction
 
+" tagbar#printfileinfo() {{{2
+function! tagbar#printfileinfo() abort
+    if !tagbar#debug#enabled()
+        echo 'Tagbar debug is disabled - unable to print fileinfo to tagbar log'
+        return
+    endif
+
+    let fileinfo = tagbar#state#get_current_file(0)
+    if empty(fileinfo)
+        call tagbar#debug#log('File contains no tag entries')
+        return
+    endif
+    let typeinfo = fileinfo.typeinfo
+
+    call tagbar#debug#log('Printing fileinfo [' . fileinfo.fpath . ' lines:' . fileinfo.lnum)
+    for line in range(1, fileinfo.lnum)
+        if has_key(fileinfo.fline, line)
+            let tag = fileinfo.fline[line]
+            call tagbar#debug#log(' '
+                        \   . ' line:' . line
+                        \   . ' kind:' . tag.fields.kind
+                        \   . ' depth:' . tag.depth
+                        \   . ' [' . tag.strfmt() . ']'
+                        \ )
+        endif
+    endfor
+    call tagbar#debug#log('All tags printed')
+
+    echo 'Tagbar fileinfo printed to debug logfile'
+endfunction
```

**Comment by raven42** [comment]
@Shane-XB-Qian  can you please share a sample file that you are seeing this error with? I am not seeing this behavior in my configuration. I see the correct function getting highlighted.

**Comment by raven42** [comment]
@Shane-XB-Qian also please share your tagbar configuration parameters from your .vimrc

**Comment by Shane-XB-Qian** [comment]
sorry, looks i can not, that's from a huge glang project.
and yes, it's not a problem if just a single file, but would/can be an issue if in a huge project.

to me, to show the parent func name (if cursor in that scope) is more important than show tag in same line.
// that also was the default behaviour of tagbar before that pr.
// so looks that's performance or somehow not a smooth solution fit for all users, perhaps better revert or had a option to disable it.

**Comment by raven42** [comment]
Ok that sounds a little different than initially described. Are you seeing the correct highlighting of the function when the cursor is somewhere else inside the function but not on another tag?

Are you able to provide a mock up file at least? I have never worked with glang before, so I need at least some sample file to debug further.

**Comment by Shane-XB-Qian** [comment]
what i can say is : same file looks worked as expected if moved it out a huge project, but did not work if in a huge project.
// such 'did not work' means did not work when cursor not on a line which is same line with that func/tag name.

**Comment by Shane-XB-Qian** [comment]
i can not mock a file, since seems it worked if just a single file.
// so looks something block it or just a performance issue, but whatever looks that pr did not fit for all users' demand/situation..

**Comment by Shane-XB-Qian** [comment]
I left my computer now, I will try it ASAP at tomorrow.
Just by the way: 
let’s kept that pr/feature disable -as that option default -which should be general best practice as well.
And that option name meaning looks not accurate, since if it was a var or cursor just on line which also was a func name define then current tag was highlighted even no that pr/feature.

**Comment by Shane-XB-Qian** [comment]
@raven42 it became worse, nothing is highlighted if so.
why not just kept previous default behaviour which as 'nearest' search mothod as default? if someone really needed 'nearest-stl' or something, then he just open a option, or manually call a cmd, or reg to au by himself.. this should be a general best practice as well. we'd better kept the tagbar quality and usability.

**Comment by raven42** [comment]
In order to debug this issue I really need a sample file that I can reproduce this on. When I test with the languages I have tested it all is working as expected. The reason for this change was to fix issues reported by others. 

So can you please share a file that reproduces this error or any debug logs or something to help me reproduce this along with your tag bar configuration from your .vimrc. I want to help, but I need more info to do so. It is working as expected for me. I don’t know why it’s not working for you if I can’t reproduce it.

**Comment by Shane-XB-Qian** [comment]
```diff
diff --git a/autoload/tagbar.vim b/autoload/tagbar.vim
index df55dd9..a193fcd 100644
--- a/autoload/tagbar.vim
+++ b/autoload/tagbar.vim
@@ -3108,23 +3108,13 @@ function! s:GetNearbyTag(request, forcecurrent, ...) abort
     " The only way to solve this would be to go over the whole tag list again,
     " making everything slower. Since this should be a rare occurence and
     " highlighting isn't /that/ important ignore it for now.
     for line in range(curline, 1, -1)
         if has_key(fileinfo.fline, line)
             let curtag = fileinfo.fline[line]
-            if a:request ==# 'nearest-stl'
-                        \ && typeinfo.getKind(curtag.fields.kind).stl || line == curline
-                let tag = curtag
-                break
-            elseif a:request ==# 'scoped-stl'
-                        \ && typeinfo.getKind(curtag.fields.kind).stl
-                        \ && curtag.fields.line <= curline
-                        \ && curline <= curtag.fields.end
-                let tag = curtag
-                break
-            elseif a:request ==# 'nearest'
+            if a:request !=# 'statusline' || typeinfo.getKind(curtag.fields.kind).stl
                 let tag = curtag
                 break
             endif
         endif
     endfor
```
// try this, i tried to revert it withOut 'nearest-stl' 'scope-stl' which against previous default.. it works if so.
// though so far not sure e.g `tag.depth` etc if needed to be cared also..

perhaps you can download 'docker' project from github? looks that's a golang proj as well, though i did not try that, if you needed mock proj.
anyway/again, i think you are adding a heavy feature, to such, best practise should be adding an option to enble it if someone really needed it -vs- (should not) enable it by default.

**Comment by raven42** [comment]
If you can't provide a sample file, then can you please use TagbarDebug to provide the logs so I can look into this more?

**Comment by Shane-XB-Qian** [comment]
```log
2020-11-12 14:56:11.961994: PrintKinds called
2020-11-12 14:56:11.962453: Printing kind: p, number of (top-level) tags: 1
2020-11-12 14:56:11.963194: Printing kind: i, number of (top-level) tags: 55
2020-11-12 14:56:11.963701: Printing kind: c, number of (top-level) tags: 32
2020-11-12 14:56:11.968812: Printing kind: v, number of (top-level) tags: 35
2020-11-12 14:56:11.974581: Printing kind: t, number of (top-level) tags: 0
2020-11-12 14:56:11.975068: Printing kind: n, number of (top-level) tags: 0
2020-11-12 14:56:11.975385: Printing kind: w, number of (top-level) tags: 0
2020-11-12 14:56:11.975709: Printing kind: e, number of (top-level) tags: 0
2020-11-12 14:56:11.975998: Printing kind: m, number of (top-level) tags: 0
2020-11-12 14:56:11.976221: Printing kind: r, number of (top-level) tags: 0
2020-11-12 14:56:11.976483: Printing kind: f, number of (top-level) tags: 28
2020-11-12 14:56:11.978795: Printing kind: ?, number of (top-level) tags: 0
2020-11-12 14:56:12.006595: Highlight pattern: '/^\%90l\s*[▼▶ ][-+# ]\?\zs[^( ]\+\ze/'
2020-11-12 14:56:12.006748: goto_win(): 1wincmd w, 1
2020-11-12 14:56:12.006865: goto_win(): 2wincmd w, 1
2020-11-12 14:56:12.042204: goto_win(): wincmd p, 1
2020-11-12 14:56:12.042442: goto_win(): 3wincmd w, 1
2020-11-12 14:56:12.042833: goto_win(): 1wincmd w, 1
2020-11-12 14:56:12.043010: goto_win(): 2wincmd w, 1
2020-11-12 14:56:12.043126: AutoUpdate finished successfully
```
// log looks did not say something specially, just such tag (in a func scope -vs- on a func define) did not highlight (compared to good one).

**Comment by Shane-XB-Qian** [comment]
all in all, such tag did not kick-off highlight due to block or performance or sth..
or whatever, again, to me or some other users, i think that feature is not much useful, at least pls not enable this by default against previous default, if someone really needed it, then just set an option for it (again 'that' option default should be not enabled).

**Comment by raven42** [comment]
@Shane-XB-Qian Unfortunately the logs provided aren't enough to go by.

I understand your comment about new features not being enabled by default. You don't need to keep repeating it. That is the intent behind this change. #683 was a fix to address an issue reported by others that there was no concept of scope for the status bar or tag highlighting. When outside of a function scope, the statusline was still showing you were inside the function and similar. So the change for #683 was to enhance the `GetNearbyTag()` to provide this functionality if enabled. It is enabled by passing the 'scoped-stl' parameter into the `tagbar#currenttag()` routine. However it defaults to the 'nearest-stl' which was intended to be the existing functionality.

I am trying to understand why that is not working in your case. It is working as expected in all of my testing. The change you propose removes the option for the 'scoped-stl' flag which would break those issues addressed by #683. Again, the intent was and always was that the default behavior would remain unchanged. I am trying to understand what is different about the files you are working with that is preventing that from working as it originally was. That is why I'm trying to find a way to reproduce it or to get the debug info needed so I can try to help provide a solution that works for everybody.

Can you please share the full log debug log? If you add `TagbarDebug <filename>` into your ~/.vimrc you can enable the debug logging when vim launches and hopefully that will give me the information I need to help with this.

Once loaded, if you can also run `:call tagbar#printfileinfo()` that will print out info into the log which I can use to hopefully help figure this out.

**Comment by raven42** [comment]
I've been playing around with the docker go files you suggested, and I am not seeing the behavior your describe. So I am still not able to debug this issue. When moving around the .go files in the docker/compose-cli repository, I am seeing the correct tags being highlighted in the tagbar window.

**Comment by raven42** [comment]
In addition to the logs and configuration listed above, can you also please provide the output from ctags for the file in question? I'm wondering if the ctags output might be different somehow which might be causing an error.

So to summarize, in order to debug further since you are unable to provide a sample file which exhibits the issue, I need the following:

- [ ] full tagbar log
- [ ] inclusion of `call tagbar#printfileinfo()` in the tagbar log
- [ ] any tagbar configuration from your .vimrc
- [ ] output of `ctags --extras=+F -f - --format=2 --excmd=pattern --fields=nksSafet --sort=no --append=no -V --language-force=go --go-kinds=picsmtfv <file>`

**Comment by Shane-XB-Qian** [comment]
i debug it by myself roughly, looks the cause was code lost a condition, though i do not know why..
// 1, if same file is Out of a huge proj:
```log
request:nearest-stl
stl:1
line:409
curline:474
```
```log
request:nearest-stl
stl:1
line:707
curline:707
```
// 2, if same file is In a huge proj:
```log
request:nearest-stl
stl:0
line:707
curline:707
```
```log
request:nearest-stl
stl:0
line:409
curline:474
```
// pls notice the difference at `stl` and `line/curline`, the code is (at line#3114 autoload/tagbar.vim)
```vim
            if a:request ==# 'nearest-stl'
                        \ && typeinfo.getKind(curtag.fields.kind).stl || line == curline
```
// i do not know why, but if you insisted 'nearest-stl' 'scoped-stl' were needed -other than 'nearest', then probably had to handle this 'lost condition' ..

**Comment by Shane-XB-Qian** [comment]
as a summary: 
when stl is 0, but curline != line, then the returned var `tag` is `{}`, as my understanding it meant nothing can be highlighted.

**Comment by Shane-XB-Qian** [comment]
sorry, i may repeatly say that 'default' too much :)    
i just tried to say a workaround which everybody would be happy.. 
so now, up to you, handle this .. or just adding an option to divide it.. :)

**Comment by raven42** [comment]
I have dug into this a little bit more, and actually I believe this is more a behavioral difference by the fix for #376. The fix for this was in PR #683 in addition to the scoped stuff. The key part is this:

Old Code:
```vim
function! s:GetNearbyTag(all, forcecurrent, ...) abort
    ...
    if a:all || typeinfo.getKind(curtag.fields.kind).stl
        let tag = curtag
        break
    endif
    ...
endfunction

function! s:HighlightTag(openfolds, ...) abort
    ...
    let tag = s:GetNearbyTag(1, 0)
    ...
endfunction
```

New Code:
```vim
function! s:GetNearbyTag(request, forcecurrent, ...) abort
    ...
    if a:request ==# 'highlight' && typeinfo.getKind(curtag.fields.kind).stl         " Note: when 'highlight', .stl is now required
        let tag = curtag
        break
    endif
    if a:request ==# 'highlight' && line == curline
        let tag = curtag
        break
    endif
    ...
endfunction

function! s:HighlightTag(openfolds, ...) abort
    ...
    let tag = s:GetNearbyTag('highlight', 0)
    ...
endfunction
```

So in order to fix #376, the behavior of the function `GetNearbyTag()` had to change as well to ignore tags above the current line which do not have the .stl flag set for that tag kind.

I suspect your configuration might be overriding the `.stl` option for something, or perhaps your ctags output is indicating a different type. Either way, if you are not seeing the correct highlighting, I am guessing it is because there is no `'neartest-stl'` that exists before your cursor.

If that is the case, then to directly fix your issue would break #376 without some method of control.

I've pushed up another possible solution (#709) where instead, now you can directly set the highlight method with a new `g:tagbar_highlight_method` configuration where you can choose your highlight method. It will default to 'nearest-stl' as that is the most likely scenario in which people will want the tags highlighted. For an example, see the issue listed in #376. And similarly in all my `.go` file testing, I was seeing the correct behavior where the scope was defined correctly, and so the proper tag was highlighted. If in fact it is your configuration that is overriding this `.stl` flag for any of the default kinds, or if your ctags output is different, that could be causing the behavior  you are seeing. So you can set the `g:tagbar_highlight_method` to `'nearest'` to revert to the old behavior prior to the fix for #376 

Will this work for your needs?

**Comment by raven42** [comment]
Also, as a side note, I've updated the `.go` tag defaults to allow a scope2kind{} and kind2scope{} for the `packages` kind. This seems to fix an issue with functions defined such as this would not work before:

```go
package SomePackage

type SomeStruct struct {
    ...
}

func (x *SomeStruct) SomeFunction() {}
```

Prior to this change, the tag for `SomeFunction()` would not be visible because the ctags path was `SomePackage.SomeStruct.SomeFunction` however tagbar wasn't previously aware that `SomePackage` could have children. This actually left a bunch of orphaned tags in the tagbar memory that were never printed to the tagbar window since they didn't have a proper parent. The change in `uctags.vim` fixes that. However I'm not familiar with `.go` files, so I am not sure I can fully verify it. Can you please give it a try and see if the tag hierarchy looks correct to you? If so, I'll pull it out into another commit specific for `.go` file support.

**Comment by raven42** [comment]
One curiosity is why the `.stl` flag is not being set in the same file when it is in a large project as you indicate. Is that project using a different `g:tagbar_type_go` definition? Or is it using a different ctags version that is outputting different `kinds` for the functions? That may be worth investigating as the changes I did for the scoped highlighting and such have absolutely nothing to do with setting the `.stl` flag for a given tag.... only how it interprets them.

Either way, the PR #709 should hopefully work even in that configuration, though it would take an extra configuration setting `let :tagbar_highlight_method = 'nearest'` to work without the `.stl` flag set.

**Comment by Shane-XB-Qian** [comment]
why `typeinfo.getKind(curtag.fields.kind).stl` had chance to be `0`, probably that's the key! -but i do not know why..
// i do not know why it would be `0`, or where it came from.. i did not dig this too much.. but it had chance to be `0`, that's the broken.

i tried you modification on `uctags.vim`, looks it did not work, or even it worked, i had no confident to say it's a solution either..

i will try `g:tagbar_highlight_method` this option, and this was what i repeatly said 'default' :)
roughly just about the code looked good, i will try it. but perhaps i wish 'nearest' should be the default -vs- (should not) 'nearest-stl'.

**Comment by Shane-XB-Qian** [comment]
i tried `g:tagbar_highlight_method = 'nearest'`, it works, though looks a bit slower than before, or just a feeling..
and if `g:tagbar_highlight_method = 'nearest-stl'`, it does not work still.
we may need more test still..

**Comment by raven42** [comment]
Ok I'll leave the `uctags.vim` change out of anything then. I don't use go so i'll defer to anybody else who does.

And yes it sounds like we can at least see that somehow (due to your environment, config, or maybe it still is a bug in tagbar somewhere), the `.stl` flag is not getting set correctly on your files. Without being able to reproduce it, that is something I can't really help with.

As for this issue with the 'regression', are you satisfied with the proposed fix of adding a new `g:tagbar_highlight_method` option? If so I will prep the PR for merge and get it in.

**Comment by Shane-XB-Qian** [comment]
> Ok I'll leave the `uctags.vim` change out of anything then

Probably just open a new ticket to record that, I was just saying for this ticket. Your found and modification perhaps still helpful, though so far I am not sure..

> due to your environment, config, or maybe it still is a bug in tagbar somewhere

Whatever my env or something else, as long as it had chance to be lost-control, I think we needed a safeguard, and ‘nearest’ is the one.

**Comment by Shane-XB-Qian** [comment]
i think put 'nearest' to be the default is following the general best practice which would not against previous default, and here actually not regard to 'correct' or 'incorrect', since which/where 'tag' to be highlighted actually was a personal preference..
// same then regardless why `.stl` lost or not, to me, i (or someone else maybe same like me) just preferred 'nearest' tag be highlighted.
but anyway, now we had a safeguard option, that's a bit better already. So up to you. thx.

as for `uctags.vim`, perhaps you were right, we can see same size golang project cost much more cpu/memory than c project if just enter/startup it to gen these.. though not only ctags was working at that timing.. and more or less perhaps it was a feeling..
// so you were ok, perhaps this one should be dug still..

**Comment by Shane-XB-Qian** [comment]
and looks i know the why now - why `.stl` lost -if you were interesting to know:
1, the init timing impacted from/by `s:type_init_done`, would make `ctags_bin` choose different, so the `stl` result perhaps is different.
2, specifically to 'go', the `stl` defined in `type_go.kinds` line#310 is different like in `uctags.vim`, so the `stl` result perhaps is different.
// but to this case, i think more possibility was caused by item#1, and so far looks no option can override that (auto detect).

**Comment by Shane-XB-Qian** [comment]
@raven42  thanks you working with me on this case. looks now issue/solution/workaround had been a bit clear. you can merge that #709 now, i closed this ticket. thx again.
