### ISSUE TITLE
Adding a new language without success

### ISSUE THREAD

**Issue by hgoumner** [preservim/tagbar#710]
Hello all,

firstly I'd like to thank all of the contributors here for the great work. I hope that one of you can help with set up a simple support for a new (very simple) language.

I have tried following the instructions on the wiki here and on various forums on the internet (such as this [link](https://www.zeusedit.com/phpBB3/viewtopic.php?t=3367) for Windows) but without success. That means that when I open the tagbar there are no entries. I've tried opening files with other filetypes such as python and C and the tags are shows correctly.

My vimrc (relevant part at the bottom) along with the .ctags file and a test file are included in the following attachment: [vim_tag_help.zip](https://github.com/preservim/tagbar/files/5533267/vim_tag_help.zip)

I'm on a Windows 10 machine using Vim 8.2. Please let me know if I should provide any more information.

Thank you in advance!

**Comment by raven42** [comment]
I think this has to do with your regular expression in the `.ctags` file. When I tried it using your file, I got the following error.

```
ctags: Warning: Unsupported parameter 'e' for "fields" option
  Option: --language-force=ac2
  Option: --ac2-kinds=c
Reading command line arguments
OPENING test.inp as ac2 language file
ctags: Warning: test.inp:1: null expansion of name pattern "\1"
ctags: Warning: test.inp:3: null expansion of name pattern "\1"
ctags: Warning: test.inp:7: null expansion of name pattern "\1"
ctags: Warning: test.inp:8: null expansion of name pattern "\1"
ctags: Warning: test.inp:10: null expansion of name pattern "\1"
ctags: Warning: test.inp:13: null expansion of name pattern "\1"
ctags: Warning: test.inp:14: null expansion of name pattern "\1"
ctags: Warning: test.inp:20: null expansion of name pattern "\1"
```

I modified the regular expression to the following and I think this is doing what you want. Though you may want to play with filtering out whitespace or something.
```
--regex-ac2=/^C---- (.*)/\1/c,controlword/
```

**Comment by hgoumner** [comment]
Thank you very much for the quick reply. Unfortunately, the change of the regex line did not help, when i open the test (or any other .inp) file my tagbar is still empty. Where did you get the error message? In Vim or in a command window? Is there something that i need to do with ctags in the command line before opening Vim?

Thanks again.

**Comment by raven42** [comment]
Hmm... ok. Perhaps this is a difference between windows and linux. I was doing all my testing on linux.

It might be best to verify the output of ctags first. Can you run the following?

If you have Universal CTAGS:
```
ctags --extras=+F -f - --format=2 --excmd=pattern --fields=nksSafet --sort=no --append=no -V --language-force=ac2 --ac2-kinds=c test.inp
```

Otherwise if you only have Exuberant CTAGS:
```
ctags --extra= --file-scope=yes -f - --format=2 --excmd=pattern --fields=nksSaft --sort=no --append=no -V --language-force=ac2 --ac2-kinds=c test.inp
```

Then please share the output. First we need to make sure that ctags is reporting the correct tags. Once we verify that, then we can look at the tagbar side of things.

The error messages I saw were a result of manually running ctags on the file using the above commands.

**Comment by hgoumner** [comment]
I put the test.inp and .ctags (and a _ctags equivalent) in the ctags.exe folder and when I execute the above command (note that I had to change --extras to --extra) the following is written to the command window:

```
C:\Users\gou\vimfiles\additional\ctags58>ctags --extra=+F -f - --format=2 --excmd=pattern --fields=nksSafet --sort=no --append=no -V --language-force=ac2 --ac2-kinds=c test.inp
ctags: Warning: Ignoring non-option in .\.ctags
ctags: Warning: Unsupported parameter 'F' for "extra" option
ctags: Warning: Unsupported parameter 'e' for "fields" option
  Option: --language-force=ac2
ctags: Unknown language "ac2" in "language-force" option

**Comment by raven42** [comment]
Ok it looks like you only have Exuberant CTAGS, not universal ctags. So you can try the second command.

But based on this output, it doesn't look like your `.ctags` file is getting picked up at all. I'm not sure where the `.ctags` and `_ctags` files should go for windows. You might have to look that up somewhere. But I think it need to go somewhere in your `PATH` or maybe even in `HOME`. You can see your environment variables in the `System Properties` window (Right click on 'My Computer' and select 'Properties', then choose 'Advanced System Properties' on the left). Then there is a button for `Environment Variables`. The ctags configuration files might go in there somewhere... or could even be somewhere in your AppData folder in your home directory (hidden folder).

Once you can get valid output from running the ctags command, then hopefully tagbar should be working.

**Comment by raven42** [comment]
.... FYI... from the ctags documentation:

```
/ctags.cnf (on MSDOS, MSWindows only)
/etc/ctags.conf
/usr/local/etc/ctags.conf
$HOME/.ctags
$HOME/ctags.cnf (on MSDOS, MSWindows only)
.ctags
ctags.cnf (on MSDOS, MSWindows only)

If any of these configuration files exist, each will be expected to contain a set of default options which are read in the order listed when ctags starts, but before the CTAGS environment variable is read or any command line options are read. This makes it possible to set up site-wide, personal or project-level defaults. It is possible to compile ctags to read an additional configuration file before any of those shown above, which will be indicated if the output produced by the −−version option lists the "custom-conf" feature. Options appearing in the CTAGS environment variable or on the command line will override options specified in these files. Only options will be read from these files. Note that the option files are read in line-oriented mode in which spaces are significant (since shell quoting is not possible). Each line of the file is read as one command line parameter (as if it were quoted with single quotes). Therefore, use new lines to indicate separate command-line arguments.
```

**Comment by hgoumner** [comment]
It really seems to be the ctags configuration which is messing things up. I got rid of exuberant tags and installed universal ctags (using chocolatey) and put the .ctags and ctags.cnf (identical to .ctags) in the `~/.ctags.d/*.ctags` directory like it says [here](https://github.com/universal-ctags/ctags) as well as in $HOME. Now when i run the command for universal ctags i don't get any warnings, just the statement that my language cannot be found.

```
C:\Users\gou\Documents\_Transfer\vim_tag_help>ctags --extras=+F -f - --format=2 --excmd=pattern --fields=nksSafet --sort=no --append=no -V --language-force=ac2 --ac2-kinds=c test.inp
  Option: --language-force=ac2
ctags.exe: Unknown language "ac2" in "language-force" option
```

I love Windows...

**Comment by raven42** [comment]
When I did the configuration for universal ctags on linux, I had to put it at `~/.ctags.d/ac2.ctags`. Maybe it is the same for windows too?

**Comment by hgoumner** [comment]
I made the change and now ctags works!!!

```
C:\Users\gou\Documents\_Transfer\vim_tag_help>ctags --extras=+F -f - --format=2 --excmd=pattern --fields=nksSafet --sort=no --append=no -V --language-force=ac2 --ac2-kinds=c test.inp
  Option: --language-force=ac2
  Option: --ac2-kinds=c
Initialize parser: ac2
Reading command line arguments
OPENING test.inp as ac2 language file [new]
HEADER  test.inp        /^C---- HEADER$/;"      c       line:1
PARAMETERS      test.inp        /^C---- PARAMETERS$/;"  c       line:3
CONTROL test.inp        /^C---- CONTROL$/;"     c       line:7
OBJECT  test.inp        /^C---- OBJECT$/;"      c       line:8
DECAY   test.inp        /^C---- DECAY$/;"       c       line:10
DISCHARGE       test.inp        /^C---- DISCHARGE$/;"   c       line:13
TABLES  test.inp        /^C---- TABLES$/;"      c       line:14
END     test.inp        /^C---- END$/;" c       line:20
```

Unfortunately, the tagbar in Vim still doesn't.

This is the relevant section in my vimrc:
```
" create tags for AC2
let g:tagbar_ac2ctags_bin='$HOME\.ctags.d\ac2.ctags'
let g:tagbar_type_ac2 = {
    \ 'ctagstype' : 'ac2',
    \ 'ctagsbin'  : tagbar_ac2ctags_bin,
    \ 'kinds' : [
        \ 'c:controlwords'
        \ ],
        \ 'sort' : 0
    \ }

**Comment by raven42** [comment]
try removing the lines:
```
let g:tagbar_ac2ctags_bin='$HOME\.ctags.d\ac2.ctags'
...
    \ 'ctagsbin'  : tagbar_ac2ctags_bin,
```

Since you've modified ctags to recognize your new language, you don't need to set a different binary to use for that file type in tagbar. Tagbar should default to just use ctags as is.

The `g:tagbar_type_<type>['ctagsbin']` entry is telling tagbar which binary to execute, not a config file to use. So in this case we don't want to change the binary, but just let tagbar use the normal ctags.

**Comment by hgoumner** [comment]
I removed the respective lines, but the issue remains. Then i tested some other filetypes to check that i didn't screw up anything by changing to universal ctags, but the tagbar works fine for them (python and C files).

**Comment by raven42** [comment]
Ok looks like the last piece is to make vim aware of the filetype. By default, vim doesn't recognize the `.inp` extension. So the `filetype` is not defined. The filetype is what tagbar uses to map a given `g:tagbar_type_<filetype>` to get the config. Try adding the following to your `.vimrc`

```vim
autocmd BufRead,BufNewFile *.inp setfiletype ac2
```

**Comment by hgoumner** [comment]
You, sir, are a genius!!! It works as expected. Thank you very much for the help. :) :) :)

**Comment by raven42** [comment]
np... glad we could get it working
