### ISSUE TITLE
is there a possibility to change the statusline look?

### ISSUE THREAD

**Issue by joe23rep** [preservim/tagbar#713]
went threw the help file and found all highlight things i can change but i havent found a way to change the statusbar itself. 

im using lightline- is there a way to change what gets displayed and maybe have different bg colors and seperators?

**Comment by raven42** [comment]
To integrate with lightline, you will need to update your lightline configuration. I use lightline as well and here is the corresponding section from my `.vimrc`

```vim
    let g:lightline = {
				\ 'active': {
				\	'left': [['mode', 'paste', 'modified'], ['readonly', 'filename'], ['functionName']],
				\	'right': [['lineinfo'], ['percent'], ['fileformat', 'fileencoding', 'filetype']]
				\ },
                                ...
                                \ 'component_function': {
                                ...
                                \	'functionName': 'LightlineFunctionName',
				\ },

    " ---- LightlineFunctionName() {{{2
	function! LightlineFunctionName()
		if !g:have_tagbar || &filetype =~# g:ignored_windows
			return ''
		endif
		return tagbar#currenttag("%s", "", 'f', 'nearest-stl')
	endfunction
```

So this way I can just use the `tagbar#currenttag()` routine directly and populate the value with that. This is what it looks like for me:
![image](https://user-images.githubusercontent.com/3730811/100009226-30ad3700-2d94-11eb-8467-6abd35698281.png)

If you want to get different colors or separators, that would be part of the lightline configuration again. I have it as a separate part of the lightline so it shows the appropriate separator. This is done by creating the separate lightline 'group' in the `'left`' section that only contains the `['functionName']` component.
