### ISSUE TITLE
Can't leave tagbar without closing it

### ISSUE THREAD

**Issue by NightH4nter** [preservim/tagbar#715]
Hi. I'm using tagbar with Neovim. When I open tagbar, I can focus it with regular keys for split navigation (in my case - leader-{jkl;}, but I can't move focus back from the tagbar split without closing it. 
_Mappings, just to be clear._ 
```vim
noremap <Leader>j <C-w>h 
noremap <Leader>k <C-w>j 
noremap <Leader>l <C-w>k 
noremap <Leader>; <C-w>l 
```

**Comment by alerque** [comment]
I use NeoVIM as well and have no problem navigating in and out of the tagbar split with normal navigation keys.

Did you try without your bindings just using `<C-w>j` etc.?

**Comment by NightH4nter** [comment]
Found the issue. Tagbar uses `<Space>` as it's own binding. Is there a way to determine if the buffer I switch to is Tagbar? If yes, then I could probably make something up to change the bindings.

**Comment by alerque** [comment]
Why make it complicated doing your own buffer detection and overrides? Tagbar supports changing the default bindings any way you like already. See `:help tagbar-keys` for info.
