### ISSUE TITLE
Struggling with changing ctags args

### ISSUE THREAD

**Issue by prizelk** [preservim/tagbar#716]
Hi, Im trying to get tagbar to work with html. I know that I have to call 
```
ctags --fields='*' --extras='*' -R 

```
for ctags to produce the kinds I want. But im struggling to integrate this idea with tagbar vimrc. I am trying 
```
'ctagsargs' : ['--fields='*' --extras='*''] 
```
But am really unsure about the correctness. Can someone please help me with configurations.
Thank you.

**Comment by raven42** [comment]
The problem with this code is that you want the single quotes `'` as part of the string. But the way strings are defined is by using single quotes to start a string and to end a string. There are two ways of dealing with this.

Either you would either have to escape the quotes using a backslash to tell the interpreter that you want the following character part of the string itself:
```vim
'ctagsargs' : ['--fields=\'*\' --extras=\'*\'']
```
or you can use double quotes in the outer string definition so single quotes can be interpreted literally:
```vim
'ctagsargs' : ["--fields='*' --extras='*'"]
```

**Comment by prizelk** [comment]
> The problem with this code is that you want the single quotes `'` as part of the string. But the way strings are defined is by using single quotes to start a string and to end a string. There are two ways of dealing with this.
> 
> Either you would either have to escape the quotes using a backslash `\` to tell the interpreter that you want the following character part of the string itself:
> 
> ```viml
> 'ctagsargs' : ['--fields=\'*\' --extras=\'*\'']
> ```
> 
> or you can use double quotes in the outer string definition so single quotes can be interpreted literally:
> 
> ```viml
> 'ctagsargs' : ["--fields='*' --extras='*'"]
> ```

Hi raven42, thank you very much for the quick response. Ive tried these variations so now I know the issue isnt ctagsargs. Im still having trouble making the kinds show up. Is something along these lines a correct configuration?
```viml
let g:tagbar_type_html = {
            \'ctagsargs' : ["--fields='*' --extras='*'"],
            \ 'kinds' : [
            \ 'a:named anchors',
            \ 'h:H1 headings',
            \ 'i:H2 headings',
            \ 'j:H3 headings',
            \ 'c:classes',
            \ 'C:stylesheets'
            \ ],
            \ 'sro'        : '::',
            \ 'kind2scope' : {
            \ 'a' : 'anchors',
            \ 'h' : 'headings',
            \ 'c' : 'class',
            \ 'j' : 'headings',
            \ 'C' : 'stylesheets'
            \ }
            \ }
```
Im quite new so I hope these questions are okay. Thanks in advance!

**Comment by raven42** [comment]
Questions are most welcome... we can only learn when we ask questions.

First, a couple questions of my own... I don't work with HTML myself, so just need to verify a few basic things.

1. Is the filetype being recognized by vim correctly? do you know what the filetype is? There is a `ctagstype` dictionary entry that can be used in your definition to set the filetype correctly.
```vim
let g:tagbar_type_html = {
            \ 'ctagstype' : 'html',
...
```

2. Is universal ctags outputting all the correct tags? Can you share a sample output and the full command line used?

We might be better off looking at resolving #627 and just provide a real definition in `uctags.vim` in the tagbar plugin.

**Comment by prizelk** [comment]
1. Im not exactly sure what you mean. I believe that by default, tagbar recognizes html and has some presets through the command:
```
:TagbarGetTypeConfig html
```
So it does display a minimal number of kinds. As shown in this file:
https://github.com/preservim/tagbar/blob/22f8084a2a6742723a5443b5ab2f2f1471bbc13c/autoload/tagbar/types/uctags.vim
2. If I call
```
ctags --fields='*' --extras='*' -R 
```
I will get the correct tags I want in a tags file: 
<img width="1103" alt="Screen Shot 2563-12-04 at 22 27 24" src="https://user-images.githubusercontent.com/69815889/101181866-f723d800-367f-11eb-9c47-266ed9c0b4dd.png">
I know tagbar does this
```
ctags --extras=+F -f - --format=2 --excmd=pattern --fields=nksSafet --sort=no --append=no -V
```
and gives me this
<img width="747" alt="Screen Shot 2563-12-04 at 22 26 10" src="https://user-images.githubusercontent.com/69815889/101181688-c479df80-367f-11eb-8313-2122b3b9bbf5.png">

Sorry if this is a bit dense. I believe uctags provides the correct tags when using the first command.

**Comment by prizelk** [comment]
1. Tagbar recognizes html and theres a tiny bit of presets for html if I run the command:
```
:TagbarGetTypeConfig html
```
This is also included in here:
https://github.com/preservim/tagbar/blob/master/autoload/tagbar/types/uctags.vim
2. I know from the file https://github.com/preservim/tagbar/blob/master/autoload/tagbar.vim
if I do
```viml
'ctagsargs' : ['--fields=+{roles}', '--extras=+{reference}'],
```
tagbar should then run:
```
ctags --fields=+{roles} --extras=+{reference} --extras=+F -f - --format=2 --excmd=pattern --fields=nksSafet --sort=no --append=no {filename}
```
I get:
<img width="1318" alt="Screen Shot 2563-12-04 at 23 16 19" src="https://user-images.githubusercontent.com/69815889/101187274-bb404100-3686-11eb-850c-b6ba820d0ae5.png">

Which is correct because running:
```
ctags --extras=+F -f - --format=2 --excmd=pattern --fields=nksSafet --sort=no --append=no {filename}
```
as tagbar would by default would give us:
<img width="920" alt="Screen Shot 2563-12-04 at 23 20 26" src="https://user-images.githubusercontent.com/69815889/101187714-4e797680-3687-11eb-8f4a-4942713c6029.png">

When running tagbar itself. I get this error:
<img width="341" alt="Screen Shot 2563-12-04 at 23 23 10" src="https://user-images.githubusercontent.com/69815889/101187991-add78680-3687-11eb-9cdc-a3972a625ac7.png">

This should be able to give you a clearer picture of my error.

**Comment by raven42** [comment]
Does this work for you?

```diff
diff --git a/autoload/tagbar/types/uctags.vim b/autoload/tagbar/types/uctags.vim
index 58fe65d..c15fd2c 100644
--- a/autoload/tagbar/types/uctags.vim
+++ b/autoload/tagbar/types/uctags.vim
@@ -527,11 +527,25 @@ function! tagbar#types#uctags#init(supported_types) abort
     " HTML {{{1
     let type_html = tagbar#prototypes#typeinfo#new()
     let type_html.ctagstype = 'html'
+    let type_html.ctagsargs = [
+                \ '--fields=+{roles}',
+                \ '--extras=+{reference}',
+                \ '--extras=+F',
+                \ '-f',
+                \ '-',
+                \ '--format=2',
+                \ '--excmd=pattern',
+                \ '--fields=nksSafet',
+                \ '--sort=no',
+                \ '--append=no',
+                \ ]
     let type_html.kinds = [
-        \ {'short' : 'a', 'long' : 'named anchors', 'fold' : 0, 'stl' : 1},
-        \ {'short' : 'h', 'long' : 'H1 headings',   'fold' : 0, 'stl' : 1},
-        \ {'short' : 'i', 'long' : 'H2 headings',   'fold' : 0, 'stl' : 1},
-        \ {'short' : 'j', 'long' : 'H3 headings',   'fold' : 0, 'stl' : 1},
+                \ {'short' : 'a', 'long' : 'named anchors', 'fold' : 0, 'stl' : 1},
+                \ {'short' : 'h', 'long' : 'H1 headings',   'fold' : 0, 'stl' : 1},
+                \ {'short' : 'i', 'long' : 'H2 headings',   'fold' : 0, 'stl' : 1},
+                \ {'short' : 'j', 'long' : 'H3 headings',   'fold' : 0, 'stl' : 1},
+                \ {'short' : 'c', 'long' : 'classes',       'fold' : 0, 'stl' : 1},
+                \ {'short' : 'C', 'long' : 'stylesheets',   'fold' : 0, 'stl' : 1},
     \ ]
     let types.html = type_html
     " Java {{{1
```

**Comment by prizelk** [comment]
<img width="278" alt="Screen Shot 2563-12-05 at 00 34 23" src="https://user-images.githubusercontent.com/69815889/101195184-a1f0c200-3691-11eb-98c9-8f1f8b21ead6.png">
Nothing shows in the tagbar.

**Comment by raven42** [comment]
did you remove all the custom entries in your `.vimrc`? and are you using universal ctags? I saw some valid entries that looked correct to me...
![image](https://user-images.githubusercontent.com/3730811/101196589-90260500-3626-11eb-992a-d31b33606383.png)

**Comment by prizelk** [comment]
You got it to work! Thank you so much for taking the time to help me resolve this raven42.
Will this be added to the plugin in the future?

**Comment by raven42** [comment]
If you want to do some more testing and validating of this, please go ahead and submit a PR. I don't really use HTML, so I probably wouldn't be the right person to validate this. But like I said, if you want to submit a PR after some testing, then we can close out #627 as well I think.

**Comment by prizelk** [comment]
> If you want to do some more testing and validating of this, please go ahead and submit a PR. I don't really use HTML, so I probably wouldn't be the right person to validate this. But like I said, if you want to submit a PR after some testing, then we can close out #627 as well I think.

Okay. Thanks again for helping me out. Have a nice day!
