### ISSUE TITLE
Tagbar highlight not following the cursor in insert mode

### ISSUE THREAD

**Issue by pacien** [preservim/tagbar#724]
Moving the cursor in the main buffer causes the relevant symbol/section to be automatically highlighted in the tagbar in normal mode, but not in insert mode, even though it would be useful in this case too.

A workaround for this is to set the following autocmd:
```
autocmd CursorHoldI * TagbarShowTag
```

However, this workaround generates warning messages when the tagbar is closed.

**Comment by alerque** [comment]
You could easily wrap that in a function to check if a tagbar buffer is open (there was another recent issue where detecting open tagbar was discussed). It's possible we could include this function in the plugin, but it would almost certainly need to be off by default as this comes with the potential for significant performance impact, and insert mode is where any delays are most noticeable.
