### ISSUE TITLE
please tag a new git release

### ISSUE THREAD

**Issue by anthraxx** [preservim/tagbar#743]
Hi, that latest release is from Jan 9, 2017. It would be great it all the valuable work from all contributors could get more reach by simply cutting a git tag once in a while.
Distros package this plugin and they always stick to latest tags and releases.

much appreciated :cat:

**Comment by alerque** [comment]
I capitulated and tagged a new release in 16f3f9b.

For the record through I still suggest most people would be better off using the *master* branch and following `HEAD` (as most VIM plugin managers do by default). We do consider that stable and do not plan on tagging frequently.

See also extensive prior discussion of this issue in #617.

**Comment by anthraxx** [comment]
Thanks and thats fine for plugin manager usage or people directly pulling git. However for distro packages we will always stick to releases so just tagging once in a while would still be highly appreciated to not leave the users of such packages back in ancient worlds. :cat:
