### ISSUE TITLE
Opening a file without tags causes errors?

### ISSUE THREAD

**Issue by jhogendorn** [preservim/tagbar#77]
When i open a file and i dont have a tags file specified, i get this:

Error detected while processing /Volumes/Storage/Users/joshua/Library/Config/Vim/.vim/bundle/TagBar/autoload/tagbar.vim:
line   75:
E121: Undefined variable: g:tagbar_iconchars
E15: Invalid expression: g:tagbar_iconchars[0]
line   76:
E121: Undefined variable: g:tagbar_iconchars
E15: Invalid expression: g:tagbar_iconchars[1]
Error detected while processing function <SNR>25_postSourceActions..7..<SNR>25_echo..tagbar#currenttag..<SNR>26_Init..<SNR>26_CheckForExCtags..<SNR>26_EscapeCtagsCmd:
line   29:
E121: Undefined variable: g:tagbar_systemenc
E15: Invalid expression: g:tagbar_systemenc != &encoding
Error detected while processing function <SNR>25_postSourceActions..7..<SNR>25_echo..tagbar#currenttag..<SNR>26_Init..<SNR>26_GetSupportedFiletypes..<SNR>26_EscapeCtagsCmd:
line   29:
E121: Undefined variable: g:tagbar_systemenc
E15: Invalid expression: g:tagbar_systemenc != &encoding
Error detected while processing function <SNR>25_postSourceActions..7..<SNR>25_echo:
line    1:
".vimrc" 396L, 10514C
Error detected while processing function <SNR>26_AutoUpdate..<SNR>26_ProcessFile..<SNR>26_ExecuteCtagsOnFile..<SNR>26_EscapeCtagsCmd:
line   29:
E121: Undefined variable: g:tagbar_systemenc
E15: Invalid expression: g:tagbar_systemenc != &encoding
Error detected while processing function <SNR>26_AutoUpdate..<SNR>26_ProcessFile..193:
line   28:
E121: Undefined variable: g:tagbar_foldlevel
E15: Invalid expression: g:tagbar_foldlevel == 0 ? 1 : kind.fold
E121: Undefined variable: g:tagbar_foldlevel
E15: Invalid expression: g:tagbar_foldlevel == 0 ? 1 : kind.fold
E121: Undefined variable: g:tagbar_foldlevel
E15: Invalid expression: g:tagbar_foldlevel == 0 ? 1 : kind.fold
E121: Undefined variable: g:tagbar_foldlevel
E15: Invalid expression: g:tagbar_foldlevel == 0 ? 1 : kind.fold
E121: Undefined variable: g:tagbar_foldlevel
E15: Invalid expression: g:tagbar_foldlevel == 0 ? 1 : kind.fold
line   40:
E121: Undefined variable: g:tagbar_foldlevel
E15: Invalid expression: g:tagbar_foldlevel
Error detected while processing function <SNR>26_AutoUpdate..<SNR>26_ProcessFile..<SNR>26_ParseTagline:
line   62:
Your ctags and Tagbar configurations are out of sync! Please read ':help tagbar-extend'.
Error detected while processing function <SNR>26_AutoUpdate..<SNR>26_ProcessFile:
line   46:
E171: Missing :endif
Error detected while processing function <SNR>26_AutoUpdate:
line   37:
E171: Missing :endif
Error detected while processing function <SNR>4_StarSetf:
line    2:
E171: Missing :endif

any ideas?

**Comment by aGlacier** [comment]
The same error. I use only file-line plugin.
Error detected while processing /home/me/git/configs/vim-plugins/tagbar/autoload/tagbar.vim:
line   43:
E121: Undefined variable: g:tagbar_iconchars
E15: Invalid expression: g:tagbar_iconchars[0]
line   44:
E121: Undefined variable: g:tagbar_iconchars
E15: Invalid expression: g:tagbar_iconchars[1]

**Comment by majutsushi** [comment]
You don't have your runtimepath set correctly. You can't put full plugin installations into the `~/.vim/plugin` directory, you have to add them to your runtimepath. Check out plugin managers like the simple [pathogen](https://github.com/tpope/vim-pathogen) or the more full-featured [Vundle](https://github.com/gmarik/Vundle.vim), [NeoBundle](https://github.com/Shougo/neobundle.vim) or [vim-plug](https://github.com/junegunn/vim-plug) that do that automatically.
