### ISSUE TITLE
how to sort elements by position?

### ISSUE THREAD

**Issue by alexzanderr** [preservim/tagbar#770]
sorry if this is a duplicate

**Comment by raven42** [comment]
When in the tagbar window, you can hit the `s` key to change the sort order. To make this persistent, you can add `let g:tagbar_sort = 0` into your `.vimrc`. See the details in the documentation at [doc/tagbar.txt](../blob/master/doc/tagbar.txt)

**Comment by alexzanderr** [comment]
i sorted them. but i didnt see any option for position. the sort didnt work for position because variables section was printed after every class or function and i had some variables at the beginning of the file.

**Comment by raven42** [comment]
The tags are always going to be categorized into a `kind` as output by ctags. So all variables throughout the entire file that don't have scope defined in the ctags output will show up in a generic `variables` tag tree hierarchy. There is no way I know of to have a global variable as a root node in the tagbar tree view and to have all tags appear in strict position as they are in the file. Any non-scoped tag will appear in a generic tree node for that tag kind.

For scoped kinds such as classes or similar structures, a root level node is created for that tag kind and any member tag kinds will show up under that node appropriately.

**Comment by alexzanderr** [comment]
thanks for reply
