### ISSUE TITLE
Tagbar window sets colorcolumn

### ISSUE THREAD

**Issue by daedroza** [preservim/tagbar#783]
Currently the color column feature from vim when set in init.vimrc is also carried forward in the tagbar window. A screenshot is attached for reference that can be found [here](https://drive.google.com/file/d/1CwoeQhO9alO91w1E7CxGJ81S8x8NNcqd/view?usp=sharing).

**Comment by raven42** [comment]
@daedroza is the preferred behavior to always not have the color column? Is there any use case where someone would want to have this enabled?

**Comment by daedroza** [comment]
The original idea behind color column is to help programmers not exceed the line limit. Hence the feature is definitely needed in the primary working window.
Since the tags are self-generated during runtime and the tagbar window cannot be modified in any way, there is no need to set the color column. Secondly, we assume that the terminal size is always greater than the color column size. That is not always true.
In my opinion, it's best if we can disable the color column in tagbar window. We don't write anything in it, so we keep it? Added benefit of removing it, is that it looks cleaner and more streamlined.

Please let me know about your opinion.

**Comment by raven42** [comment]
I think this sounds reasonable. I'll leave this discussion open for a little bit and see if anybody else has any feelings about it before we default to disable it.
