### ISSUE TITLE
Tagbar says it can not find exuberant ctags even when it is installed.

### ISSUE THREAD

**Issue by dcDeba** [preservim/tagbar#793]
$ which ctags
/remote/us01home56/deba/e_ctags/bin//ctags

$ ctags --version
Universal Ctags 5.9.0(p5.9.20211003.0), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct  5 2021, 12:13:29
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +gnulib_regex, +iconv, +option-directory, +xpath, +packcc, +optscript

Tagbar: Exuberant ctags not found at '/remote/us01home56/deba/e_ctags/bin/'!
Please check your g:tagbar_ctags_bin setting.

I have already set  g:tagbar_ctags_bin setting in my .vimrc
let g:tagbar_ctags_bin = '/remote/us01home56/deba/e_ctags/bin/'

**Comment by alerque** [comment]
I think you need to set the whole path to your executable, not just to the directory it is in:

```viml
let g:tagbar_ctags_bin = '/remote/us01home56/deba/e_ctags/bin/ctags'
```

**Comment by dcDeba** [comment]
Okay, that worked. Thanks!
