### ISSUE TITLE
How to autoload tagbar when neovim a file?

### ISSUE THREAD

**Issue by AGou-ops** [preservim/tagbar#801]
How to autoload tagbar when neovim a file? Instead of using command or hotkeys.

**Comment by raven42** [comment]
The easiest way is to add the following to your `~/.vimrc`

```
autocmd VimEnter * Tagbar
```

If you want to limit to only a specific file types, you can replace the `*` with the given file types.

**Comment by AGou-ops** [comment]
> The easiest way is to add the following to your `~/.vimrc`
> 
> ```
> autocmd VimEnter * Tagbar
> ```
> 
> If you want to limit to only a specific file types, you can replace the `*` with the given file types.

It works! Thank you.
