### ISSUE TITLE
Tag does not show up with python annotation 

### ISSUE THREAD

**Issue by SylvainGuieu** [preservim/tagbar#804]
```python
class A:
     num = 0 
```
Will show the num variable in A class in the Tagbar

```python
class A:
    num: int = 0
```

Will not. 

On neovim v0.6.1

**Comment by alerque** [comment]
This plugin is reliant on the output of your system's `ctags`. What version are you using? It's possible it isn't putting out any useful data for tagbar to show.

**Comment by SylvainGuieu** [comment]
Indeed, for:

```python
class A:
    num = 0

class B:
    num: int = 0
```

ctags output : 

```
A	test.py	/^class A:$/;"	c
B	test.py	/^class B:$/;"	c
num	test.py	/^    num = 0$/;"	v	class:A
test_main	test.py	/^from pydevmgr_core.test import test_main $/;"	i
```

So I have  switch my ctags installation from `Exuberant Ctags 5.8` to   `Universal Ctags 5.9.0` and it works : 

```
A	test.py	/^class A:$/;"	c
B	test.py	/^class B:$/;"	c
num	test.py	/^    num = 0$/;"	v	class:A
num	test.py	/^    num: int = 0$/;"	v	class:B	typeref:typename:int
```

However the import is not there anymore.  Not sure why. 

Thanks !

**Comment by alerque** [comment]
Exuberant tags is legacy and unsupported anyway, the universal ctags fork is the only way to go. Eventually we'll only be supporting it.

I don't know why the "import" was there in e-ctags or why it isn't in u-ctags, but that is something to take up with the uctags project if you think the output is incorrect. This plugin's job is just to parse and render the output, not create it.
