### ISSUE TITLE
The highlight is not updated in real-time

### ISSUE THREAD

**Issue by vdudouyt** [preservim/tagbar#81]
Let's open a source code and go to any function's body. It takes 5 seconds for the tag highlight to populate. Is it possible to do this in real-time?

**Comment by Aster89** [comment]
@majutsushi , can you give some detail on what _too low_ is? Is there a suggested threshold that you can advice?

I have it set to the default 4000 milliseconds, and I'd like to lower it at 1 second. Is that too low already? I've not tried it yet as I'd rather not fight "strange things" which I could not even relate to this setting if I hit some issue after a couple of days.

**Comment by alerque** [comment]
@Aster89 Just try it. It's entirely dependent on how fast your system is, how many other plugins you have running, how big the files you are editing are, etc. 4 seconds is pretty universally safe. I expect 1 second would work on 99% or more of systems, the 1% being ones with bad or misbehaving I/O loads. Even on my fairly dated hardware (12yo build!) and 100 I get away with a few hundred milliseconds before things get weird and a more modern system doesn't blink at 100ms. I suggest lowing it slowly and conservatively and stopping when it's comfortable. The caution is against thinking "faster is better" and trying to set 10ms or something ridiculous that is bound to cause race conditions someday when editing a big file on a system with other load.
