### ISSUE TITLE
universal-ctags settings for rust constant variable

### ISSUE THREAD

**Issue by 4LPH4-Z3R0** [preservim/tagbar#818]
In the wiki page: [Support for additional filetypes](https://github.com/preservim/tagbar/wiki#universal-ctags-variant)

There are settings for [universal-ctags](https://github.com/universal-ctags/ctags) to work on rust project: 

![image](https://user-images.githubusercontent.com/80332427/167807971-d1f2db83-2bd7-4090-bd4b-23e272444219.png)

However, these settings seem not working for rust constant variables on debian 11 and macos Montery with neovim (v0.7.0).

So I checked the original commit in the universal-ctags project : [rust: Add support for constant parsing #3253](https://github.com/universal-ctags/ctags/pull/3253/commits) and [[techee:rust2](https://github.com/techee/ctags/tree/rust2)](https://github.com/techee/ctags/commit/648cbe273d9454a0556e871c5406db83f8968aa3).

![image](https://user-images.githubusercontent.com/80332427/167808830-ecc8763a-d3a3-4009-935b-d9c4091d3f58.png)

The code shows that the key for constants should be 'C' instead of 'v'.

After I changed the settings above ('C:constants:1:0' and 'C': 'variable'), things seem to work correctly.

Should this wiki page be updated?

**Comment by alerque** [comment]
Yes, it should. Feel free…

Also since uctags supports it now Rust support should be added to core of this plugin so no user config is necessary. I would facilitate a PR that makes that happen.
