### ISSUE TITLE
Close pane with tagbar would also close the nerdtree pane

### ISSUE THREAD

**Issue by WeissZucker** [preservim/tagbar#821]
When I open a file from nerdtree in split view,(press i), and toggle tagbar for the file, then close the file, the nerdtree pane would also be closed. How can I disable this behaviour?

**Comment by alerque** [comment]
This is probably a bug. The plugin should not be closing panes it did not open / does not own. I doubt this is something you can disable with a setting, somebody probably needs to comb through and figure out why it is happening and fix it.

**Comment by alerque** [comment]
I'm out of pocket for at least a week or so.

**Comment by alvan** [comment]
Do you have any plans to merge this pull request? It at least solves a very serious bug I encountered, that is, when using bufexplorer, nerdtree, and tagbar at the same time, operations in bufexplorer (such as deleting a buffer) have unexpected errors.
