### ISSUE TITLE
Hide tagbar on tag select

### ISSUE THREAD

**Issue by godalming123** [preservim/tagbar#823]
Hi, I would like to make the tagbar hide when you select a tag

**Comment by alerque** [comment]
Please use separate issues for each topic, we can't track a list of things like this very well. I suggest editing this post to just be about one topic then opening new issues for the other two topics.

**Comment by alerque** [comment]
Does the `g:tagbar_autoclose` not cover your use case? See `:help tagbar-usage` for a description of how it works. Also opening tagbar with `:TagbarOpenAutoClose` should set that mode, so perhaps what you want to do is use that command for whatever mapping you use to launch tagbar.

**Comment by godalming123** [comment]
Yes I have just found that option thanks for your help
