### ISSUE TITLE
Link docs in wiki

### ISSUE THREAD

**Issue by godalming123** [preservim/tagbar#824]
The wiki does not mention https://github.com/preservim/tagbar/blob/master/doc/tagbar.txt it would've saved me a fair bit of time if this was linked in the wiki

**Comment by alerque** [comment]
Like many/most things VIM, the `:help` function should be the first place you look ;-)

Just for those that don't know this, I did put a reminder at the top of the wiki: https://github.com/preservim/tagbar/wiki/Home/_compare/14891430f178b1b1557c014faa50b5e5cab381de...f178db8c296da0a4a6c5c90fec730e217521ee4c
