### ISSUE TITLE
Comments starting with # within sh/shell code is included in the menu

### ISSUE THREAD

**Issue by lpyparmentier** [preservim/tagbar#832]
Hello,

If I'm writing some shell code within the following  balise \`\`\`sh ...\`\`\`, and I'm including some shell comments with #, it is included in the menu of tagbar (thinking its a chapter) while it should not. 

I did not find any related issue? and I'm not sure if it's related to tagbar plugin or with ctags ?

Laurent

**Comment by raven42** [comment]
what is the file extension? is ctags / vim recognizing it as the correct file type as a shell script? When I attempt to do a similar shell script, I do not see this behavior (at least while I am providing the correct file extension).

For example, here is one script I have. Note in the bottom right of the status line, the file type is recognized as `sh` denoting this is a shell script:
![image](https://user-images.githubusercontent.com/3730811/190654850-353a8e88-18c9-4add-9248-2142f9c23b46.png)

**Comment by lpyparmentier** [comment]
Sorry I wasn't explicit enough, i'm talking about having a `.md` file. See below:

![image](https://user-images.githubusercontent.com/64089179/190661233-3b97eca0-e6a5-435a-9d10-a121e3a51e46.png)

**Comment by raven42** [comment]
Ah ok. Yes this is a markdown file type. Ctags will recognize the `#` marker as a section header. See the [ctags markdown documenation](https://docs.ctags.io/en/latest/man/ctags-lang-rmarkdown.7.html) for more details.

There is nothing in tagbar we could really do about this. It is part of universal ctags that is picking this up.

You could open a ticket against [Universal Ctags](https://github.com/universal-ctags/ctags) that it is incorrectly interpreting a comment inside ``` shell invocation markers. Once ctags gets updated with this, then tagbar would no longer show it.

**Comment by lpyparmentier** [comment]
That's what I thought, thanks :)
