### ISSUE TITLE
How can I fold the variables tag-kind on startup?

### ISSUE THREAD

**Issue by kskollepara** [preservim/tagbar#847]
While working on a python script, the tagbar looks like : 
![image](https://user-images.githubusercontent.com/24797363/226575983-f9810314-40c7-4e26-bbae-3dfb0867e15f.png)

However, I this list gets quite large and occupies the whole tagbar buffer; and so I cannot see file structure anymore. Thus, I usually tend to manually fold the variables tag, so that I see the file structure:
![image](https://user-images.githubusercontent.com/24797363/226576845-8cc9aa66-6e82-47a7-9fca-c2d3c8d00908.png)

Is there a command that I can add to vimrc, so that variables tags are folded on startup? In the documentation, I could only find custom folding based on level, which is not what I want.

**Comment by raven42** [comment]
There is some info in the documentation that talks about this, but it may not be very obvious. The only way to do this currently is to override the tagbar kind definition and give it a new one with an updated `fold` definition for the `variables` kind.

I'm assuming this is python based on the tags. If so, the new definition would look something like this:
```vim
	let g:tagbar_type_python = {
				\ 'ctagstype'	: 'python',
				\ 'kinds'		: [
					\ 'i:modules:1:0',
					\ 'c:classes:0:1',
					\ 'f:functions:0:1',
					\ 'm:members:0:1',
					\ 'v:variables:1:0',
				\ ],
				\ 'sro'			: '.',
				\ 'kind2scope'	: {
					\ 'c' : 'class',
					\ 'f' : 'function',
					\ 'm' : 'member',
				\ },
				\ 'scope2kind'	: {
					\ 'class' : 'c',
					\ 'function' : 'f',
					\ 'member': 'm',
				\ },
			\ }

```

**Comment by kskollepara** [comment]
Thank you very much. Yes, it is python
