### ISSUE TITLE
Markdown: How to hide scopes?

### ISSUE THREAD

**Issue by wenchao-hao** [preservim/tagbar#870]
Seek for help: 
I want to use tagbar with markdown, but do not display the scope info of each title like following:

![image](https://github.com/preservim/tagbar/assets/73930449/d7518159-1896-4583-bca2-f9c1766ff63d)

How to do to disable that display?

**Comment by raven42** [comment]
This is controlled via the `g:tagbar_show_data_type` option. Please see the documentation for more information.
https://github.com/preservim/tagbar/blob/12edcb59449b335555652898f82dd6d5c59d519a/doc/tagbar.txt#L772

**Comment by wenchao-hao** [comment]
> This is controlled via the `g:tagbar_show_data_type` option. Please see the documentation for more information.
> 
> https://github.com/preservim/tagbar/blob/12edcb59449b335555652898f82dd6d5c59d519a/doc/tagbar.txt#L772

Thanks for your reply, but it seems not work.

I did not modify ```g:tagbar_show_data_type```, the behavior would not change if I set ```g:tagbar_show_data_type``` to 0 explicitly.

What's more, if I set  ```g:tagbar_show_data_type``` to 1 explicitly, it looks like following:

![image](https://github.com/preservim/tagbar/assets/73930449/abc11a32-8b65-4e5f-9803-3600e5597a5e)

**Comment by raven42** [comment]
Hmm. Ok I looked a little closer, and my memory was off. The behavior you are seeing is correct from the current implementation. The show_data_type was intended more for tags that have a data type from other languages like `int var = 0;` or similar where the datatype is derived from the word right before the tag. Which in the case of markdown does not appear to be very helpful.

That said, with the show_data_type set to 0 (default), then tagbar will populate this with the tag `kind` if it is a scoped kind (which section types in markdown are). From the current code, there is no way to disable this. Though an option probably could be added.

If we do get a chance to address this, are you wanting it to just be an empty string?

**Comment by wenchao-hao** [comment]
> Hmm. Ok I looked a little closer, and my memory was off. The behavior you are seeing is correct from the current implementation. The show_data_type was intended more for tags that have a data type from other languages like `int var = 0;` or similar where the datatype is derived from the word right before the tag. Which in the case of markdown does not appear to be very helpful.
> 
> That said, with the show_data_type set to 0 (default), then tagbar will populate this with the tag `kind` if it is a scoped kind (which section types in markdown are). From the current code, there is no way to disable this. Though an option probably could be added.
> 
> If we do get a chance to address this, are you wanting it to just be an empty string?

In fact, I want to make the display more clear, it's best to hide all contents including ":"

**Comment by wenchao-hao** [comment]
Hi @raven42 

It seems no one submit code for this feature. I am not familar with grammar and logic of vim plugin. Do you have a plan to implement this feature?

Thanks.

**Comment by raven42** [comment]
@wenchao-hao I've pushed up PR (#893) that should address this. Can you give it a try and see if this is what you're looking for? It is completely untested as I am not in my normal development environment at the moment, but I can try it out next week to test it.

**Comment by wenchao-hao** [comment]
> @wenchao-hao I've pushed up PR (#893) that should address this. Can you give it a try and see if this is what you're looking for? It is completely untested as I am not in my normal development environment at the moment, but I can try it out next week to test it.

I tried your changes, it works on my environment.

With 
g:tagbar_show_prefix = 1
g:tagbar_show_suffix = 0

The tar looks like following:

![image](https://github.com/user-attachments/assets/b0cbba92-ee86-476b-83e8-36045519237c)

This looks good for me, thanks a lot.
