### ISSUE TITLE
How to install this on neovim or Nvchad?

### ISSUE THREAD

**Issue by reactVishnu** [preservim/tagbar#871]
Please someone help

**Comment by alerque** [comment]
The same way you would any other VIM plugin. There are several plugin managers for NeoVIM, the absolute generic defaults for whatever plugin manager you use should work fine for this plugin. There are a lot of possible plugin managers so it isn't really up to us to document them all, this plugin should work with any of them. NvChad probably uses a specific manager, so follow the directions for that one.
