### ISSUE TITLE
Unsupported Kinds: 'T' for --rust-kinds option

### ISSUE THREAD

**Issue by Yihen-Liu** [preservim/tagbar#889]
When I open  tagbar on my neovim for Rust Project, error message show below:

```
Tagbar: Could not execute ctags for /Users/geeker/workspace/rust/electrs/src/daemon.rs!
Executed command: "'/usr/local/bin/ctags' '--extras=+F' '-f' '-' '--format=2' '--excmd=pattern' '--fields=nksSafet' '--sort=no' '--append=no' '--language-force=rust' '--rust-kinds=Tfgsmcti' '
--options=/Users/geeker/.local/share/nvim/plugged/rust.vim/ctags/rust.ctags' '/Users/geeker/workspace/rust/electrs/src/daemon.rs'"
Command output:
ctags: Warning: Unsupported kind: 'T' for --rust-kinds option
ctags: Language "Rust" already defined
Exit code: 1
Press ENTER or type command to continue
```

my neovim version is :  v0.10.0
universal-ctags version: v6.1.0
preservim/tagbar version: latest commit

**Comment by raven42** [comment]
Do you have a custom tagbar configuration for rust in your .vimrc? The current version of tagbar does not have a `T` listed in the definition at all (only a lowercase `t` is listed).

https://github.com/preservim/tagbar/blob/bc087d88defc0a63df3cd9284c2ecf4fcae42ce9/autoload/tagbar/types/uctags.vim#L1074-L1088

When I open a rust file on my installation without any custom rust configuration, I see the following from the tagbar logs which the `rust-kinds` matches the definition we have listed above:
```
2024-08-02 13:05:38.729994: Executing ctags command: 'ctags' '--extras=+F' '-f' '-' '--format=2' '--excmd=pattern' '--fields=nksSafet' '--sort=no' '--append=no' '-V' '--language-force=rust' '--rust-kinds=nsicfgtvMmePC' '/home/user/tmp/vfsJ6H8/2.rs'
```

**Comment by Yihen-Liu** [comment]
> Do you have a custom tagbar configuration for rust in your .vimrc? The current version of tagbar does not have a `T` listed in the definition at all (only a lowercase `t` is listed).
> 
> https://github.com/preservim/tagbar/blob/bc087d88defc0a63df3cd9284c2ecf4fcae42ce9/autoload/tagbar/types/uctags.vim#L1074-L1088
> 
> When I open a rust file on my installation without any custom rust configuration, I see the following from the tagbar logs which the `rust-kinds` matches the definition we have listed above:
> 
> ```
> 2024-08-02 13:05:38.729994: Executing ctags command: 'ctags' '--extras=+F' '-f' '-' '--format=2' '--excmd=pattern' '--fields=nksSafet' '--sort=no' '--append=no' '-V' '--language-force=rust' '--rust-kinds=nsicfgtvMmePC' '/home/user/tmp/vfsJ6H8/2.rs'
> ```

Thanks for your mention, fix it.
