### ISSUE TITLE
"ctags: cannot open temporary file : No such file..." error

### ISSUE THREAD

**Issue by elien122** [preservim/tagbar#97]
Hi. Recently I moved my Windows system from "winxp_x86" to "win7_x64."
Suddenly I encounter an weird erroneous situation with tagbar.

Please see this.
I got this screenshot with vanilla gvim73_46.zip (on vim.org) for x86, and only 'tagbar' and 'vundle' installed.

https://raw.github.com/elien122/tmp/master/tagbar_error/tagbar_error.png

The scenario is like below...
1. I set my 'TEMP' and 'TMP' environment variables to point to "C:\tmp"
       (e.g., > set TEMP=C:\tmp, set TMP=C:\tmp  )
2. When I open and execute ':TagbarToggle' with any files anywhere on another drive except "C:", this error occurs.
       (e.g., > gvim  D:\vim\tagbar.vim  )
3. Most strange thing is, if I make a directory named "tmp" on drive root (i.e., D:\tmp) and remain TEMP/TMP env. variable unchaged, no error occurs.

The only thing I can tell you is "I moved to Windows 7 (x64)." 
When I was using the winxp_x86 system, nothing annoys me with the same vim environment.

I think something goes wrong with the temporary directory as the error message is.
IMHO, there can be possible bug with Vim's tempname() handling on x64 system...

:TagbarDebug result is like this.

https://raw.github.com/elien122/tmp/master/tagbar_error/tagbardebug.log

Do you have any idea on this issue?
I will appreciate your help with this situation.

**Comment by veaxcw** [comment]
Hi,Recently,I am have this problem now in unbuntu,The Tagbar worked very well yesterday,but when I open Tagbar as usual,there is nothing in the window.so I run the debug program and check the log file. it showed that
        ctags: cannot open temporary file : No such file or directory
         ctags error when processing file
Thank u for any ideas to solve this problem.
